TRUNCATE TABLE `app_users`;
TRUNCATE TABLE `app_priemones`;
TRUNCATE TABLE `app_padaliniai`;
TRUNCATE TABLE `app_is`;
TRUNCATE TABLE `app_ispadaliniai`;
TRUNCATE TABLE `app_priemonepadaliniai`;
TRUNCATE TABLE `app_history`;

INSERT INTO `app_users` VALUES (1, "antanas", "password");
INSERT INTO `app_users` VALUES (2, "raminta", "yy");
INSERT INTO `app_users` VALUES (3, "tadas", "xx");

INSERT INTO `nocode`.`app_priemones` (`id`, `kodas`, `pavadinimas`) VALUES (NULL, 'p1-1', '1. Profesinio mokymo ir informavimo veikla');
INSERT INTO `nocode`.`app_priemones` (`id`, `kodas`, `pavadinimas`) VALUES (NULL, 'p1-2', '2. Naudojimasis konsultavimo paslaugomis');
INSERT INTO `nocode`.`app_priemones` (`id`, `kodas`, `pavadinimas`) VALUES (NULL, 'p1-3', '3. Jaunøjø ûkininkø ásikûrimas');
INSERT INTO `nocode`.`app_priemones` (`id`, `kodas`, `pavadinimas`) VALUES (NULL, 'p1-4', '4. Ankstyvas pasitraukimas ið prekinës þemës ûkio gamybos');
INSERT INTO `nocode`.`app_priemones` (`id`, `kodas`, `pavadinimas`) VALUES (NULL, 'p1-5', '5. Pusiau natûrinis ûkininkavimas');
INSERT INTO `nocode`.`app_priemones` (`id`, `kodas`, `pavadinimas`) VALUES (NULL, 'p1-6', '6. Þemës ûkio valdø modernizavimas');
INSERT INTO `nocode`.`app_priemones` (`id`, `kodas`, `pavadinimas`) VALUES (NULL, 'p1-7', '7. Miðkø ekonominës vertës didinimas');
INSERT INTO `nocode`.`app_priemones` (`id`, `kodas`, `pavadinimas`) VALUES (NULL, 'p1-8', '8. Þemës ûkio ir miðkininkystës plëtra ir pritaikymo infrastruktûra ');
INSERT INTO `nocode`.`app_priemones` (`id`, `kodas`, `pavadinimas`) VALUES (NULL, 'p1-9', '9. Þemës ûkio produktø perdirbimas ir pridëtinës vertës didinimas');
INSERT INTO `nocode`.`app_priemones` (`id`, `kodas`, `pavadinimas`) VALUES (NULL, 'p1-10', '10. Dalyvavimas maisto kokybës schemose');
INSERT INTO `nocode`.`app_priemones` (`id`, `kodas`, `pavadinimas`) VALUES (NULL, 'P2-1', '1. Agrarinës aplinkosaugos iðmokos');
INSERT INTO `nocode`.`app_priemones` (`id`, `kodas`, `pavadinimas`) VALUES (NULL, 'P2-2', '2. Pirmas þemës ûkio paskirties þemës apþeldinimas miðku');
INSERT INTO `nocode`.`app_priemones` (`id`, `kodas`, `pavadinimas`) VALUES (NULL, 'P2-3', '3. Pirmas ne þemës ûkio paskirties ir apleistos þemës ûkio paskirties þemës apþeldinimas miðku');
INSERT INTO `nocode`.`app_priemones` (`id`, `kodas`, `pavadinimas`) VALUES (NULL, 'P2-4', '4. Miðkininkystës potencialo atkûrimas ir prevenciniø priemoniø diegimas');
INSERT INTO `nocode`.`app_priemones` (`id`, `kodas`, `pavadinimas`) VALUES (NULL, 'P2-5', '5. Pelno nesiekianèios investicijos miðkuose  ');
INSERT INTO `nocode`.`app_priemones` (`id`, `kodas`, `pavadinimas`) VALUES (NULL, 'P2-6', '6. Miðkø aplinkosaugos iðmokos');
INSERT INTO `nocode`.`app_priemones` (`id`, `kodas`, `pavadinimas`) VALUES (NULL, 'P2-7', '7. Natura 2000 iðmokos ir iðmokos susijæ su Direktyva 2000/60/EC');
INSERT INTO `nocode`.`app_priemones` (`id`, `kodas`, `pavadinimas`) VALUES (NULL, 'P2-8', '8. Natura 2000 iðmokos (parama Natura 2000 miðkø teritorijose)');
INSERT INTO `nocode`.`app_priemones` (`id`, `kodas`, `pavadinimas`) VALUES (NULL, 'P2-9', '9. Parama ûkininkaujantiems vietovëse su kliûtimis, iðskyrus kalnuotas vietoves (maþiau palankios ûkininkauti vietovës)');
INSERT INTO `nocode`.`app_priemones` (`id`, `kodas`, `pavadinimas`) VALUES (NULL, 'P3-1', '1. Perëjimas prie ne þemës ûkio veiklos');
INSERT INTO `nocode`.`app_priemones` (`id`, `kodas`, `pavadinimas`) VALUES (NULL, 'P3-2', '2. Parama verslo kûrimui ir plëtrai');
INSERT INTO `nocode`.`app_priemones` (`id`, `kodas`, `pavadinimas`) VALUES (NULL, 'P3-3', '3. Kaimo turizmo veiklos skatinimas');
INSERT INTO `nocode`.`app_priemones` (`id`, `kodas`, `pavadinimas`) VALUES (NULL, 'P3-4', '4. Kaimo atnaujinimas ir plëtra (LEADER metodu)');
INSERT INTO `nocode`.`app_priemones` (`id`, `kodas`, `pavadinimas`) VALUES (NULL, 'P3-5', '5. Kaimo atnaujinimas ir plëtra (planiniu bûdu)');
INSERT INTO `nocode`.`app_priemones` (`id`, `kodas`, `pavadinimas`) VALUES (NULL, 'P4-1', '1. Vietos plëtros strategijø ágyvendinimas ');
INSERT INTO `nocode`.`app_priemones` (`id`, `kodas`, `pavadinimas`) VALUES (NULL, 'P4-2', '2. Teritorinis ir tarptautinis bendradarbiavimas');
INSERT INTO `nocode`.`app_priemones` (`id`, `kodas`, `pavadinimas`) VALUES (NULL, 'P4-3', '3. Parama VVG veiklai, ágûdþiams ágyti ir aktyviai pritaikyti');

INSERT INTO `nocode`.`app_padaliniai` (`id`, `kodas`, `pavadinimas`) VALUES (NULL, 'PA1', 'Padalinys 1');
INSERT INTO `nocode`.`app_padaliniai` (`id`, `kodas`, `pavadinimas`) VALUES (NULL, 'PA2', 'Padalinys 2');
INSERT INTO `nocode`.`app_padaliniai` (`id`, `kodas`, `pavadinimas`) VALUES (NULL, 'PA3', 'Padalinys 3');
INSERT INTO `nocode`.`app_padaliniai` (`id`, `kodas`, `pavadinimas`) VALUES (NULL, 'PA4', 'Padalinys 4');
INSERT INTO `nocode`.`app_padaliniai` (`id`, `kodas`, `pavadinimas`) VALUES (NULL, 'PA5', 'Padalinys 5');
INSERT INTO `nocode`.`app_padaliniai` (`id`, `kodas`, `pavadinimas`) VALUES (NULL, 'PA6', 'Padalinys 6');
INSERT INTO `nocode`.`app_padaliniai` (`id`, `kodas`, `pavadinimas`) VALUES (NULL, 'PA7', 'Padalinys 7');
INSERT INTO `nocode`.`app_padaliniai` (`id`, `kodas`, `pavadinimas`) VALUES (NULL, 'PA8', 'Padalinys 8');
INSERT INTO `nocode`.`app_padaliniai` (`id`, `kodas`, `pavadinimas`) VALUES (NULL, 'PA9', 'Padalinys 9');
INSERT INTO `nocode`.`app_padaliniai` (`id`, `kodas`, `pavadinimas`) VALUES (NULL, 'PA10', 'Padalinys 10');
INSERT INTO `nocode`.`app_padaliniai` (`id`, `kodas`, `pavadinimas`) VALUES (NULL, 'PA11', 'Padalinys 11');
INSERT INTO `nocode`.`app_padaliniai` (`id`, `kodas`, `pavadinimas`) VALUES (NULL, 'PA12', 'Padalinys 12');

INSERT INTO `nocode`.`app_is` (`id`, `kodas`, `pavadinimas`) VALUES (NULL, 'IS1', 'Finansø apskaitos ir valdymo');
INSERT INTO `nocode`.`app_is` (`id`, `kodas`, `pavadinimas`) VALUES (NULL, 'IS2', 'Iðmokø vykdymo');
INSERT INTO `nocode`.`app_is` (`id`, `kodas`, `pavadinimas`) VALUES (NULL, 'IS3', 'Kontrolës su registrais ');
INSERT INTO `nocode`.`app_is` (`id`, `kodas`, `pavadinimas`) VALUES (NULL, 'IS4', 'Skolininkø valdymo');
INSERT INTO `nocode`.`app_is` (`id`, `kodas`, `pavadinimas`) VALUES (NULL, 'IS5', 'Duomenø analizës');
INSERT INTO `nocode`.`app_is` (`id`, `kodas`, `pavadinimas`) VALUES (NULL, 'IS6', 'Dokumentø valdymo');
INSERT INTO `nocode`.`app_is` (`id`, `kodas`, `pavadinimas`) VALUES (NULL, 'IS7', 'Vaizdø kaupimo ir analizës');
INSERT INTO `nocode`.`app_is` (`id`, `kodas`, `pavadinimas`) VALUES (NULL, 'IS8', 'Patikros uþduoèiø planavimo ');
INSERT INTO `nocode`.`app_is` (`id`, `kodas`, `pavadinimas`) VALUES (NULL, 'IS9', 'Patikros uþduoèiø vykdymo ');
INSERT INTO `nocode`.`app_is` (`id`, `kodas`, `pavadinimas`) VALUES (NULL, 'IS10', 'Vidaus audito sistema');

INSERT INTO `nocode`.`app_ispadaliniai` (`id`, `padaliniokodas`, `iskodas`) VALUES (NULL, 'PA1', 'IS1');
INSERT INTO `nocode`.`app_ispadaliniai` (`id`, `padaliniokodas`, `iskodas`) VALUES (NULL, 'PA1', 'IS2');
INSERT INTO `nocode`.`app_ispadaliniai` (`id`, `padaliniokodas`, `iskodas`) VALUES (NULL, 'PA1', 'IS4');
INSERT INTO `nocode`.`app_ispadaliniai` (`id`, `padaliniokodas`, `iskodas`) VALUES (NULL, 'PA1', 'IS9');
INSERT INTO `nocode`.`app_ispadaliniai` (`id`, `padaliniokodas`, `iskodas`) VALUES (NULL, 'PA1', 'IS10');
INSERT INTO `nocode`.`app_ispadaliniai` (`id`, `padaliniokodas`, `iskodas`) VALUES (NULL, 'PA2', 'IS1');
INSERT INTO `nocode`.`app_ispadaliniai` (`id`, `padaliniokodas`, `iskodas`) VALUES (NULL, 'PA2', 'IS2');
INSERT INTO `nocode`.`app_ispadaliniai` (`id`, `padaliniokodas`, `iskodas`) VALUES (NULL, 'PA2', 'IS4');
INSERT INTO `nocode`.`app_ispadaliniai` (`id`, `padaliniokodas`, `iskodas`) VALUES (NULL, 'PA2', 'IS5');
INSERT INTO `nocode`.`app_ispadaliniai` (`id`, `padaliniokodas`, `iskodas`) VALUES (NULL, 'PA3', 'IS1');
INSERT INTO `nocode`.`app_ispadaliniai` (`id`, `padaliniokodas`, `iskodas`) VALUES (NULL, 'PA3', 'IS3');
INSERT INTO `nocode`.`app_ispadaliniai` (`id`, `padaliniokodas`, `iskodas`) VALUES (NULL, 'PA3', 'IS8');
INSERT INTO `nocode`.`app_ispadaliniai` (`id`, `padaliniokodas`, `iskodas`) VALUES (NULL, 'PA3', 'IS10');
INSERT INTO `nocode`.`app_ispadaliniai` (`id`, `padaliniokodas`, `iskodas`) VALUES (NULL, 'PA4', 'IS1');
INSERT INTO `nocode`.`app_ispadaliniai` (`id`, `padaliniokodas`, `iskodas`) VALUES (NULL, 'PA4', 'IS7');
INSERT INTO `nocode`.`app_ispadaliniai` (`id`, `padaliniokodas`, `iskodas`) VALUES (NULL, 'PA5', 'IS1');
INSERT INTO `nocode`.`app_ispadaliniai` (`id`, `padaliniokodas`, `iskodas`) VALUES (NULL, 'PA5', 'IS5');
INSERT INTO `nocode`.`app_ispadaliniai` (`id`, `padaliniokodas`, `iskodas`) VALUES (NULL, 'PA5', 'IS9');
INSERT INTO `nocode`.`app_ispadaliniai` (`id`, `padaliniokodas`, `iskodas`) VALUES (NULL, 'PA6', 'IS1');
INSERT INTO `nocode`.`app_ispadaliniai` (`id`, `padaliniokodas`, `iskodas`) VALUES (NULL, 'PA6', 'IS2');
INSERT INTO `nocode`.`app_ispadaliniai` (`id`, `padaliniokodas`, `iskodas`) VALUES (NULL, 'PA6', 'IS5');
INSERT INTO `nocode`.`app_ispadaliniai` (`id`, `padaliniokodas`, `iskodas`) VALUES (NULL, 'PA7', 'IS1');
INSERT INTO `nocode`.`app_ispadaliniai` (`id`, `padaliniokodas`, `iskodas`) VALUES (NULL, 'PA7', 'IS4');
INSERT INTO `nocode`.`app_ispadaliniai` (`id`, `padaliniokodas`, `iskodas`) VALUES (NULL, 'PA7', 'IS10');
INSERT INTO `nocode`.`app_ispadaliniai` (`id`, `padaliniokodas`, `iskodas`) VALUES (NULL, 'PA8', 'IS1');
INSERT INTO `nocode`.`app_ispadaliniai` (`id`, `padaliniokodas`, `iskodas`) VALUES (NULL, 'PA8', 'IS3');
INSERT INTO `nocode`.`app_ispadaliniai` (`id`, `padaliniokodas`, `iskodas`) VALUES (NULL, 'PA8', 'IS7');
INSERT INTO `nocode`.`app_ispadaliniai` (`id`, `padaliniokodas`, `iskodas`) VALUES (NULL, 'PA8', 'IS10');
INSERT INTO `nocode`.`app_ispadaliniai` (`id`, `padaliniokodas`, `iskodas`) VALUES (NULL, 'PA9', 'IS1');
INSERT INTO `nocode`.`app_ispadaliniai` (`id`, `padaliniokodas`, `iskodas`) VALUES (NULL, 'PA9', 'IS2');
INSERT INTO `nocode`.`app_ispadaliniai` (`id`, `padaliniokodas`, `iskodas`) VALUES (NULL, 'PA9', 'IS5');
INSERT INTO `nocode`.`app_ispadaliniai` (`id`, `padaliniokodas`, `iskodas`) VALUES (NULL, 'PA9', 'IS9');
INSERT INTO `nocode`.`app_ispadaliniai` (`id`, `padaliniokodas`, `iskodas`) VALUES (NULL, 'PA10', 'IS1');
INSERT INTO `nocode`.`app_ispadaliniai` (`id`, `padaliniokodas`, `iskodas`) VALUES (NULL, 'PA10', 'IS4');
INSERT INTO `nocode`.`app_ispadaliniai` (`id`, `padaliniokodas`, `iskodas`) VALUES (NULL, 'PA10', 'IS6');
INSERT INTO `nocode`.`app_ispadaliniai` (`id`, `padaliniokodas`, `iskodas`) VALUES (NULL, 'PA10', 'IS7');
INSERT INTO `nocode`.`app_ispadaliniai` (`id`, `padaliniokodas`, `iskodas`) VALUES (NULL, 'PA10', 'IS10');
INSERT INTO `nocode`.`app_ispadaliniai` (`id`, `padaliniokodas`, `iskodas`) VALUES (NULL, 'PA11', 'IS1');
INSERT INTO `nocode`.`app_ispadaliniai` (`id`, `padaliniokodas`, `iskodas`) VALUES (NULL, 'PA11', 'IS2');
INSERT INTO `nocode`.`app_ispadaliniai` (`id`, `padaliniokodas`, `iskodas`) VALUES (NULL, 'PA12', 'IS1');
INSERT INTO `nocode`.`app_ispadaliniai` (`id`, `padaliniokodas`, `iskodas`) VALUES (NULL, 'PA12', 'IS2');
INSERT INTO `nocode`.`app_ispadaliniai` (`id`, `padaliniokodas`, `iskodas`) VALUES (NULL, 'PA12', 'IS4');
INSERT INTO `nocode`.`app_ispadaliniai` (`id`, `padaliniokodas`, `iskodas`) VALUES (NULL, 'PA12', 'IS7');
INSERT INTO `nocode`.`app_ispadaliniai` (`id`, `padaliniokodas`, `iskodas`) VALUES (NULL, 'PA12', 'IS10');

INSERT INTO `nocode`.`app_priemonepadaliniai` (`id`, `padaliniokodas`, `priemoneskodas`, `valandos`) VALUES (NULL, 'PA1', 'p1-1', 1);
INSERT INTO `nocode`.`app_priemonepadaliniai` (`id`, `padaliniokodas`, `priemoneskodas`, `valandos`) VALUES (NULL, 'PA1', 'p1-3', 1);
INSERT INTO `nocode`.`app_priemonepadaliniai` (`id`, `padaliniokodas`, `priemoneskodas`, `valandos`) VALUES (NULL, 'PA1', 'p1-5', 1);
INSERT INTO `nocode`.`app_priemonepadaliniai` (`id`, `padaliniokodas`, `priemoneskodas`, `valandos`) VALUES (NULL, 'PA1', 'p1-9', 1);
INSERT INTO `nocode`.`app_priemonepadaliniai` (`id`, `padaliniokodas`, `priemoneskodas`, `valandos`) VALUES (NULL, 'PA1', 'P2-1', 1);
INSERT INTO `nocode`.`app_priemonepadaliniai` (`id`, `padaliniokodas`, `priemoneskodas`, `valandos`) VALUES (NULL, 'PA1', 'P2-7', 1);
INSERT INTO `nocode`.`app_priemonepadaliniai` (`id`, `padaliniokodas`, `priemoneskodas`, `valandos`) VALUES (NULL, 'PA1', 'P3-2', 1);
INSERT INTO `nocode`.`app_priemonepadaliniai` (`id`, `padaliniokodas`, `priemoneskodas`, `valandos`) VALUES (NULL, 'PA1', 'P4-1', 1);
INSERT INTO `nocode`.`app_priemonepadaliniai` (`id`, `padaliniokodas`, `priemoneskodas`, `valandos`) VALUES (NULL, 'PA2', 'p1-1', 1);
INSERT INTO `nocode`.`app_priemonepadaliniai` (`id`, `padaliniokodas`, `priemoneskodas`, `valandos`) VALUES (NULL, 'PA2', 'p1-2', 0.5);
INSERT INTO `nocode`.`app_priemonepadaliniai` (`id`, `padaliniokodas`, `priemoneskodas`, `valandos`) VALUES (NULL, 'PA2', 'p1-3', 0.5);
INSERT INTO `nocode`.`app_priemonepadaliniai` (`id`, `padaliniokodas`, `priemoneskodas`, `valandos`) VALUES (NULL, 'PA2', 'p1-7', 1);
INSERT INTO `nocode`.`app_priemonepadaliniai` (`id`, `padaliniokodas`, `priemoneskodas`, `valandos`) VALUES (NULL, 'PA2', 'P2-3', 1);
INSERT INTO `nocode`.`app_priemonepadaliniai` (`id`, `padaliniokodas`, `priemoneskodas`, `valandos`) VALUES (NULL, 'PA2', 'P2-9', 1);
INSERT INTO `nocode`.`app_priemonepadaliniai` (`id`, `padaliniokodas`, `priemoneskodas`, `valandos`) VALUES (NULL, 'PA2', 'P3-5', 1);
INSERT INTO `nocode`.`app_priemonepadaliniai` (`id`, `padaliniokodas`, `priemoneskodas`, `valandos`) VALUES (NULL, 'PA2', 'P4-3', 1);
INSERT INTO `nocode`.`app_priemonepadaliniai` (`id`, `padaliniokodas`, `priemoneskodas`, `valandos`) VALUES (NULL, 'PA3', 'p1-4', 0.5);
INSERT INTO `nocode`.`app_priemonepadaliniai` (`id`, `padaliniokodas`, `priemoneskodas`, `valandos`) VALUES (NULL, 'PA3', 'p1-6', 1);
INSERT INTO `nocode`.`app_priemonepadaliniai` (`id`, `padaliniokodas`, `priemoneskodas`, `valandos`) VALUES (NULL, 'PA3', 'p1-10', 1);
INSERT INTO `nocode`.`app_priemonepadaliniai` (`id`, `padaliniokodas`, `priemoneskodas`, `valandos`) VALUES (NULL, 'PA3', 'P2-5', 1);
INSERT INTO `nocode`.`app_priemonepadaliniai` (`id`, `padaliniokodas`, `priemoneskodas`, `valandos`) VALUES (NULL, 'PA3', 'P2-6', 0.5);
INSERT INTO `nocode`.`app_priemonepadaliniai` (`id`, `padaliniokodas`, `priemoneskodas`, `valandos`) VALUES (NULL, 'PA3', 'P3-3', 0.5);
INSERT INTO `nocode`.`app_priemonepadaliniai` (`id`, `padaliniokodas`, `priemoneskodas`, `valandos`) VALUES (NULL, 'PA3', 'P4-2', 0.5);
INSERT INTO `nocode`.`app_priemonepadaliniai` (`id`, `padaliniokodas`, `priemoneskodas`, `valandos`) VALUES (NULL, 'PA4', 'p1-1', 0.5);
INSERT INTO `nocode`.`app_priemonepadaliniai` (`id`, `padaliniokodas`, `priemoneskodas`, `valandos`) VALUES (NULL, 'PA4', 'p1-2', 1);
INSERT INTO `nocode`.`app_priemonepadaliniai` (`id`, `padaliniokodas`, `priemoneskodas`, `valandos`) VALUES (NULL, 'PA4', 'p1-5', 0.5);
INSERT INTO `nocode`.`app_priemonepadaliniai` (`id`, `padaliniokodas`, `priemoneskodas`, `valandos`) VALUES (NULL, 'PA4', 'p1-8', 0.5);
INSERT INTO `nocode`.`app_priemonepadaliniai` (`id`, `padaliniokodas`, `priemoneskodas`, `valandos`) VALUES (NULL, 'PA4', 'P2-3', 1);
INSERT INTO `nocode`.`app_priemonepadaliniai` (`id`, `padaliniokodas`, `priemoneskodas`, `valandos`) VALUES (NULL, 'PA4', 'P2-7', 1);
INSERT INTO `nocode`.`app_priemonepadaliniai` (`id`, `padaliniokodas`, `priemoneskodas`, `valandos`) VALUES (NULL, 'PA4', 'P3-4', 0.5);
INSERT INTO `nocode`.`app_priemonepadaliniai` (`id`, `padaliniokodas`, `priemoneskodas`, `valandos`) VALUES (NULL, 'PA4', 'P4-1', 1);
INSERT INTO `nocode`.`app_priemonepadaliniai` (`id`, `padaliniokodas`, `priemoneskodas`, `valandos`) VALUES (NULL, 'PA12', 'p1-2', 0.5);
INSERT INTO `nocode`.`app_priemonepadaliniai` (`id`, `padaliniokodas`, `priemoneskodas`, `valandos`) VALUES (NULL, 'PA12', 'p1-5', 1);
INSERT INTO `nocode`.`app_priemonepadaliniai` (`id`, `padaliniokodas`, `priemoneskodas`, `valandos`) VALUES (NULL, 'PA12', 'p1-6', 1);
INSERT INTO `nocode`.`app_priemonepadaliniai` (`id`, `padaliniokodas`, `priemoneskodas`, `valandos`) VALUES (NULL, 'PA12', 'P2-3', 0.5);
INSERT INTO `nocode`.`app_priemonepadaliniai` (`id`, `padaliniokodas`, `priemoneskodas`, `valandos`) VALUES (NULL, 'PA12', 'P2-4', 1);
INSERT INTO `nocode`.`app_priemonepadaliniai` (`id`, `padaliniokodas`, `priemoneskodas`, `valandos`) VALUES (NULL, 'PA12', 'P3-3', 0.5);
INSERT INTO `nocode`.`app_priemonepadaliniai` (`id`, `padaliniokodas`, `priemoneskodas`, `valandos`) VALUES (NULL, 'PA5', 'p1-2', 0.5);
INSERT INTO `nocode`.`app_priemonepadaliniai` (`id`, `padaliniokodas`, `priemoneskodas`, `valandos`) VALUES (NULL, 'PA5', 'p1-4', 1);
INSERT INTO `nocode`.`app_priemonepadaliniai` (`id`, `padaliniokodas`, `priemoneskodas`, `valandos`) VALUES (NULL, 'PA5', 'p1-10', 0.5);
INSERT INTO `nocode`.`app_priemonepadaliniai` (`id`, `padaliniokodas`, `priemoneskodas`, `valandos`) VALUES (NULL, 'PA5', 'P2-5', 1);
INSERT INTO `nocode`.`app_priemonepadaliniai` (`id`, `padaliniokodas`, `priemoneskodas`, `valandos`) VALUES (NULL, 'PA5', 'P3-1', 0.5);
INSERT INTO `nocode`.`app_priemonepadaliniai` (`id`, `padaliniokodas`, `priemoneskodas`, `valandos`) VALUES (NULL, 'PA5', 'P4-2', 1);
INSERT INTO `nocode`.`app_priemonepadaliniai` (`id`, `padaliniokodas`, `priemoneskodas`, `valandos`) VALUES (NULL, 'PA5', 'P4-3', 1);
INSERT INTO `nocode`.`app_priemonepadaliniai` (`id`, `padaliniokodas`, `priemoneskodas`, `valandos`) VALUES (NULL, 'PA6', 'p1-8', 1);
INSERT INTO `nocode`.`app_priemonepadaliniai` (`id`, `padaliniokodas`, `priemoneskodas`, `valandos`) VALUES (NULL, 'PA6', 'P2-2', 1);
INSERT INTO `nocode`.`app_priemonepadaliniai` (`id`, `padaliniokodas`, `priemoneskodas`, `valandos`) VALUES (NULL, 'PA6', 'P2-4', 0.5);
INSERT INTO `nocode`.`app_priemonepadaliniai` (`id`, `padaliniokodas`, `priemoneskodas`, `valandos`) VALUES (NULL, 'PA6', 'P2-9', 2);
INSERT INTO `nocode`.`app_priemonepadaliniai` (`id`, `padaliniokodas`, `priemoneskodas`, `valandos`) VALUES (NULL, 'PA6', 'P3-4', 2);
INSERT INTO `nocode`.`app_priemonepadaliniai` (`id`, `padaliniokodas`, `priemoneskodas`, `valandos`) VALUES (NULL, 'PA6', 'P4-2', 1);
INSERT INTO `nocode`.`app_priemonepadaliniai` (`id`, `padaliniokodas`, `priemoneskodas`, `valandos`) VALUES (NULL, 'PA7', 'p1-1', 1);
INSERT INTO `nocode`.`app_priemonepadaliniai` (`id`, `padaliniokodas`, `priemoneskodas`, `valandos`) VALUES (NULL, 'PA7', 'p1-2', 0.5);
INSERT INTO `nocode`.`app_priemonepadaliniai` (`id`, `padaliniokodas`, `priemoneskodas`, `valandos`) VALUES (NULL, 'PA7', 'p1-3', 1);
INSERT INTO `nocode`.`app_priemonepadaliniai` (`id`, `padaliniokodas`, `priemoneskodas`, `valandos`) VALUES (NULL, 'PA7', 'p1-5', 0.5);
INSERT INTO `nocode`.`app_priemonepadaliniai` (`id`, `padaliniokodas`, `priemoneskodas`, `valandos`) VALUES (NULL, 'PA7', 'P2-8', 2);
INSERT INTO `nocode`.`app_priemonepadaliniai` (`id`, `padaliniokodas`, `priemoneskodas`, `valandos`) VALUES (NULL, 'PA7', 'P3-5', 0.5);
INSERT INTO `nocode`.`app_priemonepadaliniai` (`id`, `padaliniokodas`, `priemoneskodas`, `valandos`) VALUES (NULL, 'PA8', 'p1-4', 1);
INSERT INTO `nocode`.`app_priemonepadaliniai` (`id`, `padaliniokodas`, `priemoneskodas`, `valandos`) VALUES (NULL, 'PA8', 'p1-6', 0.5);
INSERT INTO `nocode`.`app_priemonepadaliniai` (`id`, `padaliniokodas`, `priemoneskodas`, `valandos`) VALUES (NULL, 'PA8', 'p1-7', 0.5);
INSERT INTO `nocode`.`app_priemonepadaliniai` (`id`, `padaliniokodas`, `priemoneskodas`, `valandos`) VALUES (NULL, 'PA8', 'p1-8', 0.5);
INSERT INTO `nocode`.`app_priemonepadaliniai` (`id`, `padaliniokodas`, `priemoneskodas`, `valandos`) VALUES (NULL, 'PA8', 'p1-9', 0.5);
INSERT INTO `nocode`.`app_priemonepadaliniai` (`id`, `padaliniokodas`, `priemoneskodas`, `valandos`) VALUES (NULL, 'PA8', 'P2-3', 0.5);
INSERT INTO `nocode`.`app_priemonepadaliniai` (`id`, `padaliniokodas`, `priemoneskodas`, `valandos`) VALUES (NULL, 'PA8', 'P2-6', 0.5);
INSERT INTO `nocode`.`app_priemonepadaliniai` (`id`, `padaliniokodas`, `priemoneskodas`, `valandos`) VALUES (NULL, 'PA8', 'P3-1', 0.5);
INSERT INTO `nocode`.`app_priemonepadaliniai` (`id`, `padaliniokodas`, `priemoneskodas`, `valandos`) VALUES (NULL, 'PA8', 'P4-3', 1);
INSERT INTO `nocode`.`app_priemonepadaliniai` (`id`, `padaliniokodas`, `priemoneskodas`, `valandos`) VALUES (NULL, 'PA9', 'P2-1', 0.5);
INSERT INTO `nocode`.`app_priemonepadaliniai` (`id`, `padaliniokodas`, `priemoneskodas`, `valandos`) VALUES (NULL, 'PA9', 'P2-6', 1);
INSERT INTO `nocode`.`app_priemonepadaliniai` (`id`, `padaliniokodas`, `priemoneskodas`, `valandos`) VALUES (NULL, 'PA9', 'P2-8', 0.5);
INSERT INTO `nocode`.`app_priemonepadaliniai` (`id`, `padaliniokodas`, `priemoneskodas`, `valandos`) VALUES (NULL, 'PA9', 'P3-3', 0.5);
INSERT INTO `nocode`.`app_priemonepadaliniai` (`id`, `padaliniokodas`, `priemoneskodas`, `valandos`) VALUES (NULL, 'PA9', 'P4-2', 1);
INSERT INTO `nocode`.`app_priemonepadaliniai` (`id`, `padaliniokodas`, `priemoneskodas`, `valandos`) VALUES (NULL, 'PA10', 'p1-1', 0.5);
INSERT INTO `nocode`.`app_priemonepadaliniai` (`id`, `padaliniokodas`, `priemoneskodas`, `valandos`) VALUES (NULL, 'PA10', 'p1-2', 1);
INSERT INTO `nocode`.`app_priemonepadaliniai` (`id`, `padaliniokodas`, `priemoneskodas`, `valandos`) VALUES (NULL, 'PA10', 'p1-3', 0.5);
INSERT INTO `nocode`.`app_priemonepadaliniai` (`id`, `padaliniokodas`, `priemoneskodas`, `valandos`) VALUES (NULL, 'PA10', 'P2-1', 0.5);
INSERT INTO `nocode`.`app_priemonepadaliniai` (`id`, `padaliniokodas`, `priemoneskodas`, `valandos`) VALUES (NULL, 'PA10', 'P3-1', 0.5);
INSERT INTO `nocode`.`app_priemonepadaliniai` (`id`, `padaliniokodas`, `priemoneskodas`, `valandos`) VALUES (NULL, 'PA10', 'P3-2', 2);
INSERT INTO `nocode`.`app_priemonepadaliniai` (`id`, `padaliniokodas`, `priemoneskodas`, `valandos`) VALUES (NULL, 'PA10', 'P3-5', 1);
INSERT INTO `nocode`.`app_priemonepadaliniai` (`id`, `padaliniokodas`, `priemoneskodas`, `valandos`) VALUES (NULL, 'PA10', 'P4-1', 1);
INSERT INTO `nocode`.`app_priemonepadaliniai` (`id`, `padaliniokodas`, `priemoneskodas`, `valandos`) VALUES (NULL, 'PA10', 'P4-3', 1);
INSERT INTO `nocode`.`app_priemonepadaliniai` (`id`, `padaliniokodas`, `priemoneskodas`, `valandos`) VALUES (NULL, 'PA11', 'p1-5', 1);
INSERT INTO `nocode`.`app_priemonepadaliniai` (`id`, `padaliniokodas`, `priemoneskodas`, `valandos`) VALUES (NULL, 'PA11', 'p1-7', 0.5);
INSERT INTO `nocode`.`app_priemonepadaliniai` (`id`, `padaliniokodas`, `priemoneskodas`, `valandos`) VALUES (NULL, 'PA11', 'p1-9', 0.5);
INSERT INTO `nocode`.`app_priemonepadaliniai` (`id`, `padaliniokodas`, `priemoneskodas`, `valandos`) VALUES (NULL, 'PA11', 'p1-10', 1);
INSERT INTO `nocode`.`app_priemonepadaliniai` (`id`, `padaliniokodas`, `priemoneskodas`, `valandos`) VALUES (NULL, 'PA11', 'P2-2', 0.5);
INSERT INTO `nocode`.`app_priemonepadaliniai` (`id`, `padaliniokodas`, `priemoneskodas`, `valandos`) VALUES (NULL, 'PA11', 'P2-4', 0.5);
INSERT INTO `nocode`.`app_priemonepadaliniai` (`id`, `padaliniokodas`, `priemoneskodas`, `valandos`) VALUES (NULL, 'PA11', 'P3-1', 0.5);
INSERT INTO `nocode`.`app_priemonepadaliniai` (`id`, `padaliniokodas`, `priemoneskodas`, `valandos`) VALUES (NULL, 'PA11', 'P3-5', 0.5);


INSERT INTO `nocode`.`app_history` (`id`, `priemoneskodas`, `nuo`, `iki`, `kiekis`) VALUES (NULL, 'p1-1', '39448', '39478', '15');
INSERT INTO `nocode`.`app_history` (`id`, `priemoneskodas`, `nuo`, `iki`, `kiekis`) VALUES (NULL, 'p1-1', '39479', '39507', '27');
INSERT INTO `nocode`.`app_history` (`id`, `priemoneskodas`, `nuo`, `iki`, `kiekis`) VALUES (NULL, 'p1-1', '39508', '39538', '31');
INSERT INTO `nocode`.`app_history` (`id`, `priemoneskodas`, `nuo`, `iki`, `kiekis`) VALUES (NULL, 'p1-1', '39539', '39568', '33');
INSERT INTO `nocode`.`app_history` (`id`, `priemoneskodas`, `nuo`, `iki`, `kiekis`) VALUES (NULL, 'p1-1', '39569', '39599', '36');
INSERT INTO `nocode`.`app_history` (`id`, `priemoneskodas`, `nuo`, `iki`, `kiekis`) VALUES (NULL, 'p1-1', '39600', '39629', '13');
INSERT INTO `nocode`.`app_history` (`id`, `priemoneskodas`, `nuo`, `iki`, `kiekis`) VALUES (NULL, 'p1-1', '39630', '39660', '14');
INSERT INTO `nocode`.`app_history` (`id`, `priemoneskodas`, `nuo`, `iki`, `kiekis`) VALUES (NULL, 'p1-1', '39661', '39691', '12');
INSERT INTO `nocode`.`app_history` (`id`, `priemoneskodas`, `nuo`, `iki`, `kiekis`) VALUES (NULL, 'p1-1', '39692', '39721', '10');
INSERT INTO `nocode`.`app_history` (`id`, `priemoneskodas`, `nuo`, `iki`, `kiekis`) VALUES (NULL, 'p1-1', '39722', '39752', '11');
INSERT INTO `nocode`.`app_history` (`id`, `priemoneskodas`, `nuo`, `iki`, `kiekis`) VALUES (NULL, 'p1-1', '39753', '39782', '13');
INSERT INTO `nocode`.`app_history` (`id`, `priemoneskodas`, `nuo`, `iki`, `kiekis`) VALUES (NULL, 'p1-1', '39783', '39813', '15');
INSERT INTO `nocode`.`app_history` (`id`, `priemoneskodas`, `nuo`, `iki`, `kiekis`) VALUES (NULL, 'p1-1', '39814', '39844', '13');
INSERT INTO `nocode`.`app_history` (`id`, `priemoneskodas`, `nuo`, `iki`, `kiekis`) VALUES (NULL, 'p1-1', '39845', '39872', '26');
INSERT INTO `nocode`.`app_history` (`id`, `priemoneskodas`, `nuo`, `iki`, `kiekis`) VALUES (NULL, 'p1-1', '39873', '39903', '34');
INSERT INTO `nocode`.`app_history` (`id`, `priemoneskodas`, `nuo`, `iki`, `kiekis`) VALUES (NULL, 'p1-1', '39904', '39933', '36');
INSERT INTO `nocode`.`app_history` (`id`, `priemoneskodas`, `nuo`, `iki`, `kiekis`) VALUES (NULL, 'p1-1', '39934', '39964', '37');
INSERT INTO `nocode`.`app_history` (`id`, `priemoneskodas`, `nuo`, `iki`, `kiekis`) VALUES (NULL, 'p1-1', '39965', '39994', '16');
INSERT INTO `nocode`.`app_history` (`id`, `priemoneskodas`, `nuo`, `iki`, `kiekis`) VALUES (NULL, 'p1-1', '39995', '40025', '16');
INSERT INTO `nocode`.`app_history` (`id`, `priemoneskodas`, `nuo`, `iki`, `kiekis`) VALUES (NULL, 'p1-1', '40026', '40056', '13');
INSERT INTO `nocode`.`app_history` (`id`, `priemoneskodas`, `nuo`, `iki`, `kiekis`) VALUES (NULL, 'p1-1', '40057', '40086', '13');
INSERT INTO `nocode`.`app_history` (`id`, `priemoneskodas`, `nuo`, `iki`, `kiekis`) VALUES (NULL, 'p1-1', '40087', '40117', '12');
INSERT INTO `nocode`.`app_history` (`id`, `priemoneskodas`, `nuo`, `iki`, `kiekis`) VALUES (NULL, 'p1-1', '40118', '40147', '14');
INSERT INTO `nocode`.`app_history` (`id`, `priemoneskodas`, `nuo`, `iki`, `kiekis`) VALUES (NULL, 'p1-1', '40148', '40178', '16');
INSERT INTO `nocode`.`app_history` (`id`, `priemoneskodas`, `nuo`, `iki`, `kiekis`) VALUES (NULL, 'p1-1', '40179', '40209', '17');
INSERT INTO `nocode`.`app_history` (`id`, `priemoneskodas`, `nuo`, `iki`, `kiekis`) VALUES (NULL, 'p1-1', '40210', '40237', '29');
INSERT INTO `nocode`.`app_history` (`id`, `priemoneskodas`, `nuo`, `iki`, `kiekis`) VALUES (NULL, 'p1-1', '40238', '40268', '37');
INSERT INTO `nocode`.`app_history` (`id`, `priemoneskodas`, `nuo`, `iki`, `kiekis`) VALUES (NULL, 'p1-1', '40269', '40298', '39');
INSERT INTO `nocode`.`app_history` (`id`, `priemoneskodas`, `nuo`, `iki`, `kiekis`) VALUES (NULL, 'p1-1', '40299', '40329', '40');
INSERT INTO `nocode`.`app_history` (`id`, `priemoneskodas`, `nuo`, `iki`, `kiekis`) VALUES (NULL, 'p1-1', '40330', '40359', '18');
INSERT INTO `nocode`.`app_history` (`id`, `priemoneskodas`, `nuo`, `iki`, `kiekis`) VALUES (NULL, 'p1-1', '40360', '40390', '17');
INSERT INTO `nocode`.`app_history` (`id`, `priemoneskodas`, `nuo`, `iki`, `kiekis`) VALUES (NULL, 'p1-1', '40391', '40421', '15');
INSERT INTO `nocode`.`app_history` (`id`, `priemoneskodas`, `nuo`, `iki`, `kiekis`) VALUES (NULL, 'p1-1', '40422', '40451', '14');
INSERT INTO `nocode`.`app_history` (`id`, `priemoneskodas`, `nuo`, `iki`, `kiekis`) VALUES (NULL, 'p1-1', '40452', '40482', '13');
INSERT INTO `nocode`.`app_history` (`id`, `priemoneskodas`, `nuo`, `iki`, `kiekis`) VALUES (NULL, 'p1-1', '40483', '40512', '17');
INSERT INTO `nocode`.`app_history` (`id`, `priemoneskodas`, `nuo`, `iki`, `kiekis`) VALUES (NULL, 'p1-1', '40513', '40543', '18');
INSERT INTO `nocode`.`app_history` (`id`, `priemoneskodas`, `nuo`, `iki`, `kiekis`) VALUES (NULL, 'p1-1', '40544', '40574', '19');
INSERT INTO `nocode`.`app_history` (`id`, `priemoneskodas`, `nuo`, `iki`, `kiekis`) VALUES (NULL, 'p1-1', '40575', '40602', '21');
INSERT INTO `nocode`.`app_history` (`id`, `priemoneskodas`, `nuo`, `iki`, `kiekis`) VALUES (NULL, 'p1-1', '40603', '40633', '30');
INSERT INTO `nocode`.`app_history` (`id`, `priemoneskodas`, `nuo`, `iki`, `kiekis`) VALUES (NULL, 'p1-1', '40634', '40663', '36');
INSERT INTO `nocode`.`app_history` (`id`, `priemoneskodas`, `nuo`, `iki`, `kiekis`) VALUES (NULL, 'p1-1', '40664', '40694', '40');
INSERT INTO `nocode`.`app_history` (`id`, `priemoneskodas`, `nuo`, `iki`, `kiekis`) VALUES (NULL, 'p1-1', '40695', '40724', '40');
INSERT INTO `nocode`.`app_history` (`id`, `priemoneskodas`, `nuo`, `iki`, `kiekis`) VALUES (NULL, 'p1-1', '40725', '40755', '19');
INSERT INTO `nocode`.`app_history` (`id`, `priemoneskodas`, `nuo`, `iki`, `kiekis`) VALUES (NULL, 'p1-1', '40756', '40786', '16');
INSERT INTO `nocode`.`app_history` (`id`, `priemoneskodas`, `nuo`, `iki`, `kiekis`) VALUES (NULL, 'p1-1', '40787', '40816', '15');
INSERT INTO `nocode`.`app_history` (`id`, `priemoneskodas`, `nuo`, `iki`, `kiekis`) VALUES (NULL, 'p1-1', '40817', '40847', '15');
INSERT INTO `nocode`.`app_history` (`id`, `priemoneskodas`, `nuo`, `iki`, `kiekis`) VALUES (NULL, 'p1-2', '39448', '39478', '73');
INSERT INTO `nocode`.`app_history` (`id`, `priemoneskodas`, `nuo`, `iki`, `kiekis`) VALUES (NULL, 'p1-2', '39479', '39507', '118');
INSERT INTO `nocode`.`app_history` (`id`, `priemoneskodas`, `nuo`, `iki`, `kiekis`) VALUES (NULL, 'p1-2', '39508', '39538', '137');
INSERT INTO `nocode`.`app_history` (`id`, `priemoneskodas`, `nuo`, `iki`, `kiekis`) VALUES (NULL, 'p1-2', '39539', '39568', '139');
INSERT INTO `nocode`.`app_history` (`id`, `priemoneskodas`, `nuo`, `iki`, `kiekis`) VALUES (NULL, 'p1-2', '39569', '39599', '155');
INSERT INTO `nocode`.`app_history` (`id`, `priemoneskodas`, `nuo`, `iki`, `kiekis`) VALUES (NULL, 'p1-2', '39600', '39629', '56');
INSERT INTO `nocode`.`app_history` (`id`, `priemoneskodas`, `nuo`, `iki`, `kiekis`) VALUES (NULL, 'p1-2', '39630', '39660', '65');
INSERT INTO `nocode`.`app_history` (`id`, `priemoneskodas`, `nuo`, `iki`, `kiekis`) VALUES (NULL, 'p1-2', '39661', '39691', '59');
INSERT INTO `nocode`.`app_history` (`id`, `priemoneskodas`, `nuo`, `iki`, `kiekis`) VALUES (NULL, 'p1-2', '39692', '39721', '50');
INSERT INTO `nocode`.`app_history` (`id`, `priemoneskodas`, `nuo`, `iki`, `kiekis`) VALUES (NULL, 'p1-2', '39722', '39752', '53');
INSERT INTO `nocode`.`app_history` (`id`, `priemoneskodas`, `nuo`, `iki`, `kiekis`) VALUES (NULL, 'p1-2', '39753', '39782', '60');
INSERT INTO `nocode`.`app_history` (`id`, `priemoneskodas`, `nuo`, `iki`, `kiekis`) VALUES (NULL, 'p1-2', '39783', '39813', '72');
INSERT INTO `nocode`.`app_history` (`id`, `priemoneskodas`, `nuo`, `iki`, `kiekis`) VALUES (NULL, 'p1-2', '39814', '39844', '67');
INSERT INTO `nocode`.`app_history` (`id`, `priemoneskodas`, `nuo`, `iki`, `kiekis`) VALUES (NULL, 'p1-2', '39845', '39872', '114');
INSERT INTO `nocode`.`app_history` (`id`, `priemoneskodas`, `nuo`, `iki`, `kiekis`) VALUES (NULL, 'p1-2', '39873', '39903', '143');
INSERT INTO `nocode`.`app_history` (`id`, `priemoneskodas`, `nuo`, `iki`, `kiekis`) VALUES (NULL, 'p1-2', '39904', '39933', '153');
INSERT INTO `nocode`.`app_history` (`id`, `priemoneskodas`, `nuo`, `iki`, `kiekis`) VALUES (NULL, 'p1-2', '39934', '39964', '154');
INSERT INTO `nocode`.`app_history` (`id`, `priemoneskodas`, `nuo`, `iki`, `kiekis`) VALUES (NULL, 'p1-2', '39965', '39994', '72');
INSERT INTO `nocode`.`app_history` (`id`, `priemoneskodas`, `nuo`, `iki`, `kiekis`) VALUES (NULL, 'p1-2', '39995', '40025', '72');
INSERT INTO `nocode`.`app_history` (`id`, `priemoneskodas`, `nuo`, `iki`, `kiekis`) VALUES (NULL, 'p1-2', '40026', '40056', '58');
INSERT INTO `nocode`.`app_history` (`id`, `priemoneskodas`, `nuo`, `iki`, `kiekis`) VALUES (NULL, 'p1-2', '40057', '40086', '61');
INSERT INTO `nocode`.`app_history` (`id`, `priemoneskodas`, `nuo`, `iki`, `kiekis`) VALUES (NULL, 'p1-2', '40087', '40117', '52');
INSERT INTO `nocode`.`app_history` (`id`, `priemoneskodas`, `nuo`, `iki`, `kiekis`) VALUES (NULL, 'p1-2', '40118', '40147', '68');
INSERT INTO `nocode`.`app_history` (`id`, `priemoneskodas`, `nuo`, `iki`, `kiekis`) VALUES (NULL, 'p1-2', '40148', '40178', '68');
INSERT INTO `nocode`.`app_history` (`id`, `priemoneskodas`, `nuo`, `iki`, `kiekis`) VALUES (NULL, 'p1-2', '40179', '40209', '72');
INSERT INTO `nocode`.`app_history` (`id`, `priemoneskodas`, `nuo`, `iki`, `kiekis`) VALUES (NULL, 'p1-2', '40210', '40237', '122');
INSERT INTO `nocode`.`app_history` (`id`, `priemoneskodas`, `nuo`, `iki`, `kiekis`) VALUES (NULL, 'p1-2', '40238', '40268', '157');
INSERT INTO `nocode`.`app_history` (`id`, `priemoneskodas`, `nuo`, `iki`, `kiekis`) VALUES (NULL, 'p1-2', '40269', '40298', '168');
INSERT INTO `nocode`.`app_history` (`id`, `priemoneskodas`, `nuo`, `iki`, `kiekis`) VALUES (NULL, 'p1-2', '40299', '40329', '165');
INSERT INTO `nocode`.`app_history` (`id`, `priemoneskodas`, `nuo`, `iki`, `kiekis`) VALUES (NULL, 'p1-2', '40330', '40359', '86');
INSERT INTO `nocode`.`app_history` (`id`, `priemoneskodas`, `nuo`, `iki`, `kiekis`) VALUES (NULL, 'p1-2', '40360', '40390', '77');
INSERT INTO `nocode`.`app_history` (`id`, `priemoneskodas`, `nuo`, `iki`, `kiekis`) VALUES (NULL, 'p1-2', '40391', '40421', '64');
INSERT INTO `nocode`.`app_history` (`id`, `priemoneskodas`, `nuo`, `iki`, `kiekis`) VALUES (NULL, 'p1-2', '40422', '40451', '65');
INSERT INTO `nocode`.`app_history` (`id`, `priemoneskodas`, `nuo`, `iki`, `kiekis`) VALUES (NULL, 'p1-2', '40452', '40482', '64');
INSERT INTO `nocode`.`app_history` (`id`, `priemoneskodas`, `nuo`, `iki`, `kiekis`) VALUES (NULL, 'p1-2', '40483', '40512', '72');
INSERT INTO `nocode`.`app_history` (`id`, `priemoneskodas`, `nuo`, `iki`, `kiekis`) VALUES (NULL, 'p1-2', '40513', '40543', '86');
INSERT INTO `nocode`.`app_history` (`id`, `priemoneskodas`, `nuo`, `iki`, `kiekis`) VALUES (NULL, 'p1-2', '40544', '40574', '85');
INSERT INTO `nocode`.`app_history` (`id`, `priemoneskodas`, `nuo`, `iki`, `kiekis`) VALUES (NULL, 'p1-2', '40575', '40602', '91');
INSERT INTO `nocode`.`app_history` (`id`, `priemoneskodas`, `nuo`, `iki`, `kiekis`) VALUES (NULL, 'p1-2', '40603', '40633', '125');
INSERT INTO `nocode`.`app_history` (`id`, `priemoneskodas`, `nuo`, `iki`, `kiekis`) VALUES (NULL, 'p1-2', '40634', '40663', '150');
INSERT INTO `nocode`.`app_history` (`id`, `priemoneskodas`, `nuo`, `iki`, `kiekis`) VALUES (NULL, 'p1-2', '40664', '40694', '168');
INSERT INTO `nocode`.`app_history` (`id`, `priemoneskodas`, `nuo`, `iki`, `kiekis`) VALUES (NULL, 'p1-2', '40695', '40724', '170');
INSERT INTO `nocode`.`app_history` (`id`, `priemoneskodas`, `nuo`, `iki`, `kiekis`) VALUES (NULL, 'p1-2', '40725', '40755', '88');
INSERT INTO `nocode`.`app_history` (`id`, `priemoneskodas`, `nuo`, `iki`, `kiekis`) VALUES (NULL, 'p1-2', '40756', '40786', '72');
INSERT INTO `nocode`.`app_history` (`id`, `priemoneskodas`, `nuo`, `iki`, `kiekis`) VALUES (NULL, 'p1-2', '40787', '40816', '69');
INSERT INTO `nocode`.`app_history` (`id`, `priemoneskodas`, `nuo`, `iki`, `kiekis`) VALUES (NULL, 'p1-2', '40817', '40847', '65');
INSERT INTO `nocode`.`app_history` (`id`, `priemoneskodas`, `nuo`, `iki`, `kiekis`) VALUES (NULL, 'p1-3', '39448', '39478', '155');
INSERT INTO `nocode`.`app_history` (`id`, `priemoneskodas`, `nuo`, `iki`, `kiekis`) VALUES (NULL, 'p1-3', '39479', '39507', '56');
INSERT INTO `nocode`.`app_history` (`id`, `priemoneskodas`, `nuo`, `iki`, `kiekis`) VALUES (NULL, 'p1-3', '39508', '39538', '65');
INSERT INTO `nocode`.`app_history` (`id`, `priemoneskodas`, `nuo`, `iki`, `kiekis`) VALUES (NULL, 'p1-3', '39539', '39568', '59');
INSERT INTO `nocode`.`app_history` (`id`, `priemoneskodas`, `nuo`, `iki`, `kiekis`) VALUES (NULL, 'p1-3', '39569', '39599', '50');
INSERT INTO `nocode`.`app_history` (`id`, `priemoneskodas`, `nuo`, `iki`, `kiekis`) VALUES (NULL, 'p1-3', '39600', '39629', '53');
INSERT INTO `nocode`.`app_history` (`id`, `priemoneskodas`, `nuo`, `iki`, `kiekis`) VALUES (NULL, 'p1-3', '39630', '39660', '60');
INSERT INTO `nocode`.`app_history` (`id`, `priemoneskodas`, `nuo`, `iki`, `kiekis`) VALUES (NULL, 'p1-3', '39661', '39691', '72');
INSERT INTO `nocode`.`app_history` (`id`, `priemoneskodas`, `nuo`, `iki`, `kiekis`) VALUES (NULL, 'p1-3', '39692', '39721', '67');
INSERT INTO `nocode`.`app_history` (`id`, `priemoneskodas`, `nuo`, `iki`, `kiekis`) VALUES (NULL, 'p1-3', '39722', '39752', '114');
INSERT INTO `nocode`.`app_history` (`id`, `priemoneskodas`, `nuo`, `iki`, `kiekis`) VALUES (NULL, 'p1-3', '39753', '39782', '143');
INSERT INTO `nocode`.`app_history` (`id`, `priemoneskodas`, `nuo`, `iki`, `kiekis`) VALUES (NULL, 'p1-3', '39783', '39813', '153');
INSERT INTO `nocode`.`app_history` (`id`, `priemoneskodas`, `nuo`, `iki`, `kiekis`) VALUES (NULL, 'p1-3', '39814', '39844', '150');
INSERT INTO `nocode`.`app_history` (`id`, `priemoneskodas`, `nuo`, `iki`, `kiekis`) VALUES (NULL, 'p1-3', '39845', '39872', '53');
INSERT INTO `nocode`.`app_history` (`id`, `priemoneskodas`, `nuo`, `iki`, `kiekis`) VALUES (NULL, 'p1-3', '39873', '39903', '60');
INSERT INTO `nocode`.`app_history` (`id`, `priemoneskodas`, `nuo`, `iki`, `kiekis`) VALUES (NULL, 'p1-3', '39904', '39933', '55');
INSERT INTO `nocode`.`app_history` (`id`, `priemoneskodas`, `nuo`, `iki`, `kiekis`) VALUES (NULL, 'p1-3', '39934', '39964', '46');
INSERT INTO `nocode`.`app_history` (`id`, `priemoneskodas`, `nuo`, `iki`, `kiekis`) VALUES (NULL, 'p1-3', '39965', '39994', '49');
INSERT INTO `nocode`.`app_history` (`id`, `priemoneskodas`, `nuo`, `iki`, `kiekis`) VALUES (NULL, 'p1-3', '39995', '40025', '58');
INSERT INTO `nocode`.`app_history` (`id`, `priemoneskodas`, `nuo`, `iki`, `kiekis`) VALUES (NULL, 'p1-3', '40026', '40056', '66');
INSERT INTO `nocode`.`app_history` (`id`, `priemoneskodas`, `nuo`, `iki`, `kiekis`) VALUES (NULL, 'p1-3', '40057', '40086', '66');
INSERT INTO `nocode`.`app_history` (`id`, `priemoneskodas`, `nuo`, `iki`, `kiekis`) VALUES (NULL, 'p1-3', '40087', '40117', '99');
INSERT INTO `nocode`.`app_history` (`id`, `priemoneskodas`, `nuo`, `iki`, `kiekis`) VALUES (NULL, 'p1-3', '40118', '40147', '134');
INSERT INTO `nocode`.`app_history` (`id`, `priemoneskodas`, `nuo`, `iki`, `kiekis`) VALUES (NULL, 'p1-3', '40148', '40178', '147');
INSERT INTO `nocode`.`app_history` (`id`, `priemoneskodas`, `nuo`, `iki`, `kiekis`) VALUES (NULL, 'p1-3', '40179', '40209', '49');
INSERT INTO `nocode`.`app_history` (`id`, `priemoneskodas`, `nuo`, `iki`, `kiekis`) VALUES (NULL, 'p1-3', '40210', '40237', '53');
INSERT INTO `nocode`.`app_history` (`id`, `priemoneskodas`, `nuo`, `iki`, `kiekis`) VALUES (NULL, 'p1-3', '40238', '40268', '49');
INSERT INTO `nocode`.`app_history` (`id`, `priemoneskodas`, `nuo`, `iki`, `kiekis`) VALUES (NULL, 'p1-3', '40269', '40298', '41');
INSERT INTO `nocode`.`app_history` (`id`, `priemoneskodas`, `nuo`, `iki`, `kiekis`) VALUES (NULL, 'p1-3', '40299', '40329', '41');
INSERT INTO `nocode`.`app_history` (`id`, `priemoneskodas`, `nuo`, `iki`, `kiekis`) VALUES (NULL, 'p1-3', '40330', '40359', '50');
INSERT INTO `nocode`.`app_history` (`id`, `priemoneskodas`, `nuo`, `iki`, `kiekis`) VALUES (NULL, 'p1-3', '40360', '40390', '58');
INSERT INTO `nocode`.`app_history` (`id`, `priemoneskodas`, `nuo`, `iki`, `kiekis`) VALUES (NULL, 'p1-3', '40391', '40421', '61');
INSERT INTO `nocode`.`app_history` (`id`, `priemoneskodas`, `nuo`, `iki`, `kiekis`) VALUES (NULL, 'p1-3', '40422', '40451', '89');
INSERT INTO `nocode`.`app_history` (`id`, `priemoneskodas`, `nuo`, `iki`, `kiekis`) VALUES (NULL, 'p1-3', '40452', '40482', '124');
INSERT INTO `nocode`.`app_history` (`id`, `priemoneskodas`, `nuo`, `iki`, `kiekis`) VALUES (NULL, 'p1-3', '40483', '40512', '133');
INSERT INTO `nocode`.`app_history` (`id`, `priemoneskodas`, `nuo`, `iki`, `kiekis`) VALUES (NULL, 'p1-3', '40513', '40543', '141');
INSERT INTO `nocode`.`app_history` (`id`, `priemoneskodas`, `nuo`, `iki`, `kiekis`) VALUES (NULL, 'p1-3', '40544', '40574', '41');
INSERT INTO `nocode`.`app_history` (`id`, `priemoneskodas`, `nuo`, `iki`, `kiekis`) VALUES (NULL, 'p1-3', '40575', '40602', '46');
INSERT INTO `nocode`.`app_history` (`id`, `priemoneskodas`, `nuo`, `iki`, `kiekis`) VALUES (NULL, 'p1-3', '40603', '40633', '40');
INSERT INTO `nocode`.`app_history` (`id`, `priemoneskodas`, `nuo`, `iki`, `kiekis`) VALUES (NULL, 'p1-3', '40634', '40663', '35');
INSERT INTO `nocode`.`app_history` (`id`, `priemoneskodas`, `nuo`, `iki`, `kiekis`) VALUES (NULL, 'p1-3', '40664', '40694', '34');
INSERT INTO `nocode`.`app_history` (`id`, `priemoneskodas`, `nuo`, `iki`, `kiekis`) VALUES (NULL, 'p1-3', '40695', '40724', '45');
INSERT INTO `nocode`.`app_history` (`id`, `priemoneskodas`, `nuo`, `iki`, `kiekis`) VALUES (NULL, 'p1-3', '40725', '40755', '50');
INSERT INTO `nocode`.`app_history` (`id`, `priemoneskodas`, `nuo`, `iki`, `kiekis`) VALUES (NULL, 'p1-3', '40756', '40786', '53');
INSERT INTO `nocode`.`app_history` (`id`, `priemoneskodas`, `nuo`, `iki`, `kiekis`) VALUES (NULL, 'p1-3', '40787', '40816', '81');
INSERT INTO `nocode`.`app_history` (`id`, `priemoneskodas`, `nuo`, `iki`, `kiekis`) VALUES (NULL, 'p1-3', '40817', '40847', '119');
INSERT INTO `nocode`.`app_history` (`id`, `priemoneskodas`, `nuo`, `iki`, `kiekis`) VALUES (NULL, 'p1-4', '39448', '39478', '70');
INSERT INTO `nocode`.`app_history` (`id`, `priemoneskodas`, `nuo`, `iki`, `kiekis`) VALUES (NULL, 'p1-4', '39479', '39507', '108');
INSERT INTO `nocode`.`app_history` (`id`, `priemoneskodas`, `nuo`, `iki`, `kiekis`) VALUES (NULL, 'p1-4', '39508', '39538', '158');
INSERT INTO `nocode`.`app_history` (`id`, `priemoneskodas`, `nuo`, `iki`, `kiekis`) VALUES (NULL, 'p1-4', '39539', '39568', '207');
INSERT INTO `nocode`.`app_history` (`id`, `priemoneskodas`, `nuo`, `iki`, `kiekis`) VALUES (NULL, 'p1-4', '39569', '39599', '74');
INSERT INTO `nocode`.`app_history` (`id`, `priemoneskodas`, `nuo`, `iki`, `kiekis`) VALUES (NULL, 'p1-4', '39600', '39629', '87');
INSERT INTO `nocode`.`app_history` (`id`, `priemoneskodas`, `nuo`, `iki`, `kiekis`) VALUES (NULL, 'p1-4', '39630', '39660', '79');
INSERT INTO `nocode`.`app_history` (`id`, `priemoneskodas`, `nuo`, `iki`, `kiekis`) VALUES (NULL, 'p1-4', '39661', '39691', '67');
INSERT INTO `nocode`.`app_history` (`id`, `priemoneskodas`, `nuo`, `iki`, `kiekis`) VALUES (NULL, 'p1-4', '39692', '39721', '71');
INSERT INTO `nocode`.`app_history` (`id`, `priemoneskodas`, `nuo`, `iki`, `kiekis`) VALUES (NULL, 'p1-4', '39722', '39752', '80');
INSERT INTO `nocode`.`app_history` (`id`, `priemoneskodas`, `nuo`, `iki`, `kiekis`) VALUES (NULL, 'p1-4', '39753', '39782', '96');
INSERT INTO `nocode`.`app_history` (`id`, `priemoneskodas`, `nuo`, `iki`, `kiekis`) VALUES (NULL, 'p1-4', '39783', '39813', '89');
INSERT INTO `nocode`.`app_history` (`id`, `priemoneskodas`, `nuo`, `iki`, `kiekis`) VALUES (NULL, 'p1-4', '39814', '39844', '152');
INSERT INTO `nocode`.`app_history` (`id`, `priemoneskodas`, `nuo`, `iki`, `kiekis`) VALUES (NULL, 'p1-4', '39845', '39872', '190');
INSERT INTO `nocode`.`app_history` (`id`, `priemoneskodas`, `nuo`, `iki`, `kiekis`) VALUES (NULL, 'p1-4', '39873', '39903', '205');
INSERT INTO `nocode`.`app_history` (`id`, `priemoneskodas`, `nuo`, `iki`, `kiekis`) VALUES (NULL, 'p1-4', '39904', '39933', '200');
INSERT INTO `nocode`.`app_history` (`id`, `priemoneskodas`, `nuo`, `iki`, `kiekis`) VALUES (NULL, 'p1-4', '39934', '39964', '70');
INSERT INTO `nocode`.`app_history` (`id`, `priemoneskodas`, `nuo`, `iki`, `kiekis`) VALUES (NULL, 'p1-4', '39965', '39994', '81');
INSERT INTO `nocode`.`app_history` (`id`, `priemoneskodas`, `nuo`, `iki`, `kiekis`) VALUES (NULL, 'p1-4', '39995', '40025', '74');
INSERT INTO `nocode`.`app_history` (`id`, `priemoneskodas`, `nuo`, `iki`, `kiekis`) VALUES (NULL, 'p1-4', '40026', '40056', '62');
INSERT INTO `nocode`.`app_history` (`id`, `priemoneskodas`, `nuo`, `iki`, `kiekis`) VALUES (NULL, 'p1-4', '40057', '40086', '65');
INSERT INTO `nocode`.`app_history` (`id`, `priemoneskodas`, `nuo`, `iki`, `kiekis`) VALUES (NULL, 'p1-4', '40087', '40117', '77');
INSERT INTO `nocode`.`app_history` (`id`, `priemoneskodas`, `nuo`, `iki`, `kiekis`) VALUES (NULL, 'p1-4', '40118', '40147', '88');
INSERT INTO `nocode`.`app_history` (`id`, `priemoneskodas`, `nuo`, `iki`, `kiekis`) VALUES (NULL, 'p1-4', '40148', '40178', '89');
INSERT INTO `nocode`.`app_history` (`id`, `priemoneskodas`, `nuo`, `iki`, `kiekis`) VALUES (NULL, 'p1-4', '40179', '40209', '132');
INSERT INTO `nocode`.`app_history` (`id`, `priemoneskodas`, `nuo`, `iki`, `kiekis`) VALUES (NULL, 'p1-4', '40210', '40237', '179');
INSERT INTO `nocode`.`app_history` (`id`, `priemoneskodas`, `nuo`, `iki`, `kiekis`) VALUES (NULL, 'p1-4', '40238', '40268', '196');
INSERT INTO `nocode`.`app_history` (`id`, `priemoneskodas`, `nuo`, `iki`, `kiekis`) VALUES (NULL, 'p1-4', '40269', '40298', '66');
INSERT INTO `nocode`.`app_history` (`id`, `priemoneskodas`, `nuo`, `iki`, `kiekis`) VALUES (NULL, 'p1-4', '40299', '40329', '71');
INSERT INTO `nocode`.`app_history` (`id`, `priemoneskodas`, `nuo`, `iki`, `kiekis`) VALUES (NULL, 'p1-4', '40330', '40359', '66');
INSERT INTO `nocode`.`app_history` (`id`, `priemoneskodas`, `nuo`, `iki`, `kiekis`) VALUES (NULL, 'p1-4', '40360', '40390', '55');
INSERT INTO `nocode`.`app_history` (`id`, `priemoneskodas`, `nuo`, `iki`, `kiekis`) VALUES (NULL, 'p1-4', '40391', '40421', '54');
INSERT INTO `nocode`.`app_history` (`id`, `priemoneskodas`, `nuo`, `iki`, `kiekis`) VALUES (NULL, 'p1-4', '40422', '40451', '67');
INSERT INTO `nocode`.`app_history` (`id`, `priemoneskodas`, `nuo`, `iki`, `kiekis`) VALUES (NULL, 'p1-4', '40452', '40482', '77');
INSERT INTO `nocode`.`app_history` (`id`, `priemoneskodas`, `nuo`, `iki`, `kiekis`) VALUES (NULL, 'p1-4', '40483', '40512', '81');
INSERT INTO `nocode`.`app_history` (`id`, `priemoneskodas`, `nuo`, `iki`, `kiekis`) VALUES (NULL, 'p1-4', '40513', '40543', '118');
INSERT INTO `nocode`.`app_history` (`id`, `priemoneskodas`, `nuo`, `iki`, `kiekis`) VALUES (NULL, 'p1-4', '40544', '40574', '166');
INSERT INTO `nocode`.`app_history` (`id`, `priemoneskodas`, `nuo`, `iki`, `kiekis`) VALUES (NULL, 'p1-4', '40575', '40602', '178');
INSERT INTO `nocode`.`app_history` (`id`, `priemoneskodas`, `nuo`, `iki`, `kiekis`) VALUES (NULL, 'p1-4', '40603', '40633', '188');
INSERT INTO `nocode`.`app_history` (`id`, `priemoneskodas`, `nuo`, `iki`, `kiekis`) VALUES (NULL, 'p1-4', '40634', '40663', '55');
INSERT INTO `nocode`.`app_history` (`id`, `priemoneskodas`, `nuo`, `iki`, `kiekis`) VALUES (NULL, 'p1-4', '40664', '40694', '62');
INSERT INTO `nocode`.`app_history` (`id`, `priemoneskodas`, `nuo`, `iki`, `kiekis`) VALUES (NULL, 'p1-4', '40695', '40724', '54');
INSERT INTO `nocode`.`app_history` (`id`, `priemoneskodas`, `nuo`, `iki`, `kiekis`) VALUES (NULL, 'p1-4', '40725', '40755', '47');
INSERT INTO `nocode`.`app_history` (`id`, `priemoneskodas`, `nuo`, `iki`, `kiekis`) VALUES (NULL, 'p1-4', '40756', '40786', '45');
INSERT INTO `nocode`.`app_history` (`id`, `priemoneskodas`, `nuo`, `iki`, `kiekis`) VALUES (NULL, 'p1-4', '40787', '40816', '60');
INSERT INTO `nocode`.`app_history` (`id`, `priemoneskodas`, `nuo`, `iki`, `kiekis`) VALUES (NULL, 'p1-4', '40817', '40847', '67');
INSERT INTO `nocode`.`app_history` (`id`, `priemoneskodas`, `nuo`, `iki`, `kiekis`) VALUES (NULL, 'p1-5', '39448', '39478', '117');
INSERT INTO `nocode`.`app_history` (`id`, `priemoneskodas`, `nuo`, `iki`, `kiekis`) VALUES (NULL, 'p1-5', '39479', '39507', '195');
INSERT INTO `nocode`.`app_history` (`id`, `priemoneskodas`, `nuo`, `iki`, `kiekis`) VALUES (NULL, 'p1-5', '39508', '39538', '228');
INSERT INTO `nocode`.`app_history` (`id`, `priemoneskodas`, `nuo`, `iki`, `kiekis`) VALUES (NULL, 'p1-5', '39539', '39568', '257');
INSERT INTO `nocode`.`app_history` (`id`, `priemoneskodas`, `nuo`, `iki`, `kiekis`) VALUES (NULL, 'p1-5', '39569', '39599', '233');
INSERT INTO `nocode`.`app_history` (`id`, `priemoneskodas`, `nuo`, `iki`, `kiekis`) VALUES (NULL, 'p1-5', '39600', '39629', '105');
INSERT INTO `nocode`.`app_history` (`id`, `priemoneskodas`, `nuo`, `iki`, `kiekis`) VALUES (NULL, 'p1-5', '39630', '39660', '109');
INSERT INTO `nocode`.`app_history` (`id`, `priemoneskodas`, `nuo`, `iki`, `kiekis`) VALUES (NULL, 'p1-5', '39661', '39691', '96');
INSERT INTO `nocode`.`app_history` (`id`, `priemoneskodas`, `nuo`, `iki`, `kiekis`) VALUES (NULL, 'p1-5', '39692', '39721', '91');
INSERT INTO `nocode`.`app_history` (`id`, `priemoneskodas`, `nuo`, `iki`, `kiekis`) VALUES (NULL, 'p1-5', '39722', '39752', '104');
INSERT INTO `nocode`.`app_history` (`id`, `priemoneskodas`, `nuo`, `iki`, `kiekis`) VALUES (NULL, 'p1-5', '39753', '39782', '113');
INSERT INTO `nocode`.`app_history` (`id`, `priemoneskodas`, `nuo`, `iki`, `kiekis`) VALUES (NULL, 'p1-5', '39783', '39813', '115');
INSERT INTO `nocode`.`app_history` (`id`, `priemoneskodas`, `nuo`, `iki`, `kiekis`) VALUES (NULL, 'p1-5', '39814', '39844', '138');
INSERT INTO `nocode`.`app_history` (`id`, `priemoneskodas`, `nuo`, `iki`, `kiekis`) VALUES (NULL, 'p1-5', '39845', '39872', '219');
INSERT INTO `nocode`.`app_history` (`id`, `priemoneskodas`, `nuo`, `iki`, `kiekis`) VALUES (NULL, 'p1-5', '39873', '39903', '265');
INSERT INTO `nocode`.`app_history` (`id`, `priemoneskodas`, `nuo`, `iki`, `kiekis`) VALUES (NULL, 'p1-5', '39904', '39933', '268');
INSERT INTO `nocode`.`app_history` (`id`, `priemoneskodas`, `nuo`, `iki`, `kiekis`) VALUES (NULL, 'p1-5', '39934', '39964', '235');
INSERT INTO `nocode`.`app_history` (`id`, `priemoneskodas`, `nuo`, `iki`, `kiekis`) VALUES (NULL, 'p1-5', '39965', '39994', '126');
INSERT INTO `nocode`.`app_history` (`id`, `priemoneskodas`, `nuo`, `iki`, `kiekis`) VALUES (NULL, 'p1-5', '39995', '40025', '118');
INSERT INTO `nocode`.`app_history` (`id`, `priemoneskodas`, `nuo`, `iki`, `kiekis`) VALUES (NULL, 'p1-5', '40026', '40056', '101');
INSERT INTO `nocode`.`app_history` (`id`, `priemoneskodas`, `nuo`, `iki`, `kiekis`) VALUES (NULL, 'p1-5', '40057', '40086', '100');
INSERT INTO `nocode`.`app_history` (`id`, `priemoneskodas`, `nuo`, `iki`, `kiekis`) VALUES (NULL, 'p1-5', '40087', '40117', '100');
INSERT INTO `nocode`.`app_history` (`id`, `priemoneskodas`, `nuo`, `iki`, `kiekis`) VALUES (NULL, 'p1-5', '40118', '40147', '117');
INSERT INTO `nocode`.`app_history` (`id`, `priemoneskodas`, `nuo`, `iki`, `kiekis`) VALUES (NULL, 'p1-5', '40148', '40178', '122');
INSERT INTO `nocode`.`app_history` (`id`, `priemoneskodas`, `nuo`, `iki`, `kiekis`) VALUES (NULL, 'p1-5', '40179', '40209', '150');
INSERT INTO `nocode`.`app_history` (`id`, `priemoneskodas`, `nuo`, `iki`, `kiekis`) VALUES (NULL, 'p1-5', '40210', '40237', '226');