TRUNCATE TABLE `app_users`;
TRUNCATE TABLE `app_priemones`;
TRUNCATE TABLE `app_padaliniai`;
TRUNCATE TABLE `app_is`;
TRUNCATE TABLE `app_ispadaliniai`;
TRUNCATE TABLE `app_priemonepadaliniai`;
TRUNCATE TABLE `app_history`;

INSERT INTO `app_users` VALUES (1, "antanas", "password");
INSERT INTO `app_users` VALUES (2, "raminta", "yy");
INSERT INTO `app_users` VALUES (3, "tadas", "xx");

INSERT INTO `nocode`.`app_priemones` (`id`, `kodas`, `pavadinimas`) VALUES (NULL, 'p1-1', '1. Profesinio mokymo ir informavimo veikla');
INSERT INTO `nocode`.`app_priemones` (`id`, `kodas`, `pavadinimas`) VALUES (NULL, 'p1-2', '2. Naudojimasis konsultavimo paslaugomis');
INSERT INTO `nocode`.`app_priemones` (`id`, `kodas`, `pavadinimas`) VALUES (NULL, 'p1-3', '3. Jaunøjø ûkininkø ásikûrimas');
INSERT INTO `nocode`.`app_priemones` (`id`, `kodas`, `pavadinimas`) VALUES (NULL, 'p1-4', '4. Ankstyvas pasitraukimas ið prekinës þemës ûkio gamybos');
INSERT INTO `nocode`.`app_priemones` (`id`, `kodas`, `pavadinimas`) VALUES (NULL, 'p1-5', '5. Pusiau natûrinis ûkininkavimas');
INSERT INTO `nocode`.`app_priemones` (`id`, `kodas`, `pavadinimas`) VALUES (NULL, 'p1-6', '6. Þemës ûkio valdø modernizavimas');
INSERT INTO `nocode`.`app_priemones` (`id`, `kodas`, `pavadinimas`) VALUES (NULL, 'p1-7', '7. Miðkø ekonominës vertës didinimas');
INSERT INTO `nocode`.`app_priemones` (`id`, `kodas`, `pavadinimas`) VALUES (NULL, 'p1-8', '8. Þemës ûkio ir miðkininkystës plëtra ir pritaikymo infrastruktûra ');
INSERT INTO `nocode`.`app_priemones` (`id`, `kodas`, `pavadinimas`) VALUES (NULL, 'p1-9', '9. Þemës ûkio produktø perdirbimas ir pridëtinës vertës didinimas');
INSERT INTO `nocode`.`app_priemones` (`id`, `kodas`, `pavadinimas`) VALUES (NULL, 'p1-10', '10. Dalyvavimas maisto kokybës schemose');
INSERT INTO `nocode`.`app_priemones` (`id`, `kodas`, `pavadinimas`) VALUES (NULL, 'P2-1', '1. Agrarinës aplinkosaugos iðmokos');
INSERT INTO `nocode`.`app_priemones` (`id`, `kodas`, `pavadinimas`) VALUES (NULL, 'P2-2', '2. Pirmas þemës ûkio paskirties þemës apþeldinimas miðku');
INSERT INTO `nocode`.`app_priemones` (`id`, `kodas`, `pavadinimas`) VALUES (NULL, 'P2-3', '3. Pirmas ne þemës ûkio paskirties ir apleistos þemës ûkio paskirties þemës apþeldinimas miðku');
INSERT INTO `nocode`.`app_priemones` (`id`, `kodas`, `pavadinimas`) VALUES (NULL, 'P2-4', '4. Miðkininkystës potencialo atkûrimas ir prevenciniø priemoniø diegimas');
INSERT INTO `nocode`.`app_priemones` (`id`, `kodas`, `pavadinimas`) VALUES (NULL, 'P2-5', '5. Pelno nesiekianèios investicijos miðkuose  ');
INSERT INTO `nocode`.`app_priemones` (`id`, `kodas`, `pavadinimas`) VALUES (NULL, 'P2-6', '6. Miðkø aplinkosaugos iðmokos');
INSERT INTO `nocode`.`app_priemones` (`id`, `kodas`, `pavadinimas`) VALUES (NULL, 'P2-7', '7. Natura 2000 iðmokos ir iðmokos susijæ su Direktyva 2000/60/EC');
INSERT INTO `nocode`.`app_priemones` (`id`, `kodas`, `pavadinimas`) VALUES (NULL, 'P2-8', '8. Natura 2000 iðmokos (parama Natura 2000 miðkø teritorijose)');
INSERT INTO `nocode`.`app_priemones` (`id`, `kodas`, `pavadinimas`) VALUES (NULL, 'P2-9', '9. Parama ûkininkaujantiems vietovëse su kliûtimis, iðskyrus kalnuotas vietoves (maþiau palankios ûkininkauti vietovës)');
INSERT INTO `nocode`.`app_priemones` (`id`, `kodas`, `pavadinimas`) VALUES (NULL, 'P3-1', '1. Perëjimas prie ne þemës ûkio veiklos');
INSERT INTO `nocode`.`app_priemones` (`id`, `kodas`, `pavadinimas`) VALUES (NULL, 'P3-2', '2. Parama verslo kûrimui ir plëtrai');
INSERT INTO `nocode`.`app_priemones` (`id`, `kodas`, `pavadinimas`) VALUES (NULL, 'P3-3', '3. Kaimo turizmo veiklos skatinimas');
INSERT INTO `nocode`.`app_priemones` (`id`, `kodas`, `pavadinimas`) VALUES (NULL, 'P3-4', '4. Kaimo atnaujinimas ir plëtra (LEADER metodu)');
INSERT INTO `nocode`.`app_priemones` (`id`, `kodas`, `pavadinimas`) VALUES (NULL, 'P3-5', '5. Kaimo atnaujinimas ir plëtra (planiniu bûdu)');
INSERT INTO `nocode`.`app_priemones` (`id`, `kodas`, `pavadinimas`) VALUES (NULL, 'P4-1', '1. Vietos plëtros strategijø ágyvendinimas ');
INSERT INTO `nocode`.`app_priemones` (`id`, `kodas`, `pavadinimas`) VALUES (NULL, 'P4-2', '2. Teritorinis ir tarptautinis bendradarbiavimas');
INSERT INTO `nocode`.`app_priemones` (`id`, `kodas`, `pavadinimas`) VALUES (NULL, 'P4-3', '3. Parama VVG veiklai, ágûdþiams ágyti ir aktyviai pritaikyti');

INSERT INTO `nocode`.`app_padaliniai` (`id`, `kodas`, `pavadinimas`) VALUES (NULL, 'PA1', 'Padalinys 1');
INSERT INTO `nocode`.`app_padaliniai` (`id`, `kodas`, `pavadinimas`) VALUES (NULL, 'PA2', 'Padalinys 2');
INSERT INTO `nocode`.`app_padaliniai` (`id`, `kodas`, `pavadinimas`) VALUES (NULL, 'PA3', 'Padalinys 3');
INSERT INTO `nocode`.`app_padaliniai` (`id`, `kodas`, `pavadinimas`) VALUES (NULL, 'PA4', 'Padalinys 4');
INSERT INTO `nocode`.`app_padaliniai` (`id`, `kodas`, `pavadinimas`) VALUES (NULL, 'PA5', 'Padalinys 5');
INSERT INTO `nocode`.`app_padaliniai` (`id`, `kodas`, `pavadinimas`) VALUES (NULL, 'PA6', 'Padalinys 6');
INSERT INTO `nocode`.`app_padaliniai` (`id`, `kodas`, `pavadinimas`) VALUES (NULL, 'PA7', 'Padalinys 7');
INSERT INTO `nocode`.`app_padaliniai` (`id`, `kodas`, `pavadinimas`) VALUES (NULL, 'PA8', 'Padalinys 8');
INSERT INTO `nocode`.`app_padaliniai` (`id`, `kodas`, `pavadinimas`) VALUES (NULL, 'PA9', 'Padalinys 9');
INSERT INTO `nocode`.`app_padaliniai` (`id`, `kodas`, `pavadinimas`) VALUES (NULL, 'PA10', 'Padalinys 10');
INSERT INTO `nocode`.`app_padaliniai` (`id`, `kodas`, `pavadinimas`) VALUES (NULL, 'PA11', 'Padalinys 11');
INSERT INTO `nocode`.`app_padaliniai` (`id`, `kodas`, `pavadinimas`) VALUES (NULL, 'PA12', 'Padalinys 12');

INSERT INTO `nocode`.`app_is` (`id`, `kodas`, `pavadinimas`) VALUES (NULL, 'IS1', 'Finansø apskaitos ir valdymo');
INSERT INTO `nocode`.`app_is` (`id`, `kodas`, `pavadinimas`) VALUES (NULL, 'IS2', 'Iðmokø vykdymo');
INSERT INTO `nocode`.`app_is` (`id`, `kodas`, `pavadinimas`) VALUES (NULL, 'IS3', 'Kontrolës su registrais ');
INSERT INTO `nocode`.`app_is` (`id`, `kodas`, `pavadinimas`) VALUES (NULL, 'IS4', 'Skolininkø valdymo');
INSERT INTO `nocode`.`app_is` (`id`, `kodas`, `pavadinimas`) VALUES (NULL, 'IS5', 'Duomenø analizës');
INSERT INTO `nocode`.`app_is` (`id`, `kodas`, `pavadinimas`) VALUES (NULL, 'IS6', 'Dokumentø valdymo');
INSERT INTO `nocode`.`app_is` (`id`, `kodas`, `pavadinimas`) VALUES (NULL, 'IS7', 'Vaizdø kaupimo ir analizës');
INSERT INTO `nocode`.`app_is` (`id`, `kodas`, `pavadinimas`) VALUES (NULL, 'IS8', 'Patikros uþduoèiø planavimo ');
INSERT INTO `nocode`.`app_is` (`id`, `kodas`, `pavadinimas`) VALUES (NULL, 'IS9', 'Patikros uþduoèiø vykdymo ');
INSERT INTO `nocode`.`app_is` (`id`, `kodas`, `pavadinimas`) VALUES (NULL, 'IS10', 'Vidaus audito sistema');

INSERT INTO `nocode`.`app_ispadaliniai` (`id`, `padaliniokodas`, `iskodas`) VALUES (NULL, 'PA1', 'IS1');
INSERT INTO `nocode`.`app_ispadaliniai` (`id`, `padaliniokodas`, `iskodas`) VALUES (NULL, 'PA1', 'IS2');
INSERT INTO `nocode`.`app_ispadaliniai` (`id`, `padaliniokodas`, `iskodas`) VALUES (NULL, 'PA1', 'IS4');
INSERT INTO `nocode`.`app_ispadaliniai` (`id`, `padaliniokodas`, `iskodas`) VALUES (NULL, 'PA1', 'IS9');
INSERT INTO `nocode`.`app_ispadaliniai` (`id`, `padaliniokodas`, `iskodas`) VALUES (NULL, 'PA1', 'IS10');
INSERT INTO `nocode`.`app_ispadaliniai` (`id`, `padaliniokodas`, `iskodas`) VALUES (NULL, 'PA2', 'IS1');
INSERT INTO `nocode`.`app_ispadaliniai` (`id`, `padaliniokodas`, `iskodas`) VALUES (NULL, 'PA2', 'IS2');
INSERT INTO `nocode`.`app_ispadaliniai` (`id`, `padaliniokodas`, `iskodas`) VALUES (NULL, 'PA2', 'IS4');
INSERT INTO `nocode`.`app_ispadaliniai` (`id`, `padaliniokodas`, `iskodas`) VALUES (NULL, 'PA2', 'IS5');
INSERT INTO `nocode`.`app_ispadaliniai` (`id`, `padaliniokodas`, `iskodas`) VALUES (NULL, 'PA3', 'IS1');
INSERT INTO `nocode`.`app_ispadaliniai` (`id`, `padaliniokodas`, `iskodas`) VALUES (NULL, 'PA3', 'IS3');
INSERT INTO `nocode`.`app_ispadaliniai` (`id`, `padaliniokodas`, `iskodas`) VALUES (NULL, 'PA3', 'IS8');
INSERT INTO `nocode`.`app_ispadaliniai` (`id`, `padaliniokodas`, `iskodas`) VALUES (NULL, 'PA3', 'IS10');
INSERT INTO `nocode`.`app_ispadaliniai` (`id`, `padaliniokodas`, `iskodas`) VALUES (NULL, 'PA4', 'IS1');
INSERT INTO `nocode`.`app_ispadaliniai` (`id`, `padaliniokodas`, `iskodas`) VALUES (NULL, 'PA4', 'IS7');
INSERT INTO `nocode`.`app_ispadaliniai` (`id`, `padaliniokodas`, `iskodas`) VALUES (NULL, 'PA5', 'IS1');
INSERT INTO `nocode`.`app_ispadaliniai` (`id`, `padaliniokodas`, `iskodas`) VALUES (NULL, 'PA5', 'IS5');
INSERT INTO `nocode`.`app_ispadaliniai` (`id`, `padaliniokodas`, `iskodas`) VALUES (NULL, 'PA5', 'IS9');
INSERT INTO `nocode`.`app_ispadaliniai` (`id`, `padaliniokodas`, `iskodas`) VALUES (NULL, 'PA6', 'IS1');
INSERT INTO `nocode`.`app_ispadaliniai` (`id`, `padaliniokodas`, `iskodas`) VALUES (NULL, 'PA6', 'IS2');
INSERT INTO `nocode`.`app_ispadaliniai` (`id`, `padaliniokodas`, `iskodas`) VALUES (NULL, 'PA6', 'IS5');
INSERT INTO `nocode`.`app_ispadaliniai` (`id`, `padaliniokodas`, `iskodas`) VALUES (NULL, 'PA7', 'IS1');
INSERT INTO `nocode`.`app_ispadaliniai` (`id`, `padaliniokodas`, `iskodas`) VALUES (NULL, 'PA7', 'IS4');
INSERT INTO `nocode`.`app_ispadaliniai` (`id`, `padaliniokodas`, `iskodas`) VALUES (NULL, 'PA7', 'IS10');
INSERT INTO `nocode`.`app_ispadaliniai` (`id`, `padaliniokodas`, `iskodas`) VALUES (NULL, 'PA8', 'IS1');
INSERT INTO `nocode`.`app_ispadaliniai` (`id`, `padaliniokodas`, `iskodas`) VALUES (NULL, 'PA8', 'IS3');
INSERT INTO `nocode`.`app_ispadaliniai` (`id`, `padaliniokodas`, `iskodas`) VALUES (NULL, 'PA8', 'IS7');
INSERT INTO `nocode`.`app_ispadaliniai` (`id`, `padaliniokodas`, `iskodas`) VALUES (NULL, 'PA8', 'IS10');
INSERT INTO `nocode`.`app_ispadaliniai` (`id`, `padaliniokodas`, `iskodas`) VALUES (NULL, 'PA9', 'IS1');
INSERT INTO `nocode`.`app_ispadaliniai` (`id`, `padaliniokodas`, `iskodas`) VALUES (NULL, 'PA9', 'IS2');
INSERT INTO `nocode`.`app_ispadaliniai` (`id`, `padaliniokodas`, `iskodas`) VALUES (NULL, 'PA9', 'IS5');
INSERT INTO `nocode`.`app_ispadaliniai` (`id`, `padaliniokodas`, `iskodas`) VALUES (NULL, 'PA9', 'IS9');
INSERT INTO `nocode`.`app_ispadaliniai` (`id`, `padaliniokodas`, `iskodas`) VALUES (NULL, 'PA10', 'IS1');
INSERT INTO `nocode`.`app_ispadaliniai` (`id`, `padaliniokodas`, `iskodas`) VALUES (NULL, 'PA10', 'IS4');
INSERT INTO `nocode`.`app_ispadaliniai` (`id`, `padaliniokodas`, `iskodas`) VALUES (NULL, 'PA10', 'IS6');
INSERT INTO `nocode`.`app_ispadaliniai` (`id`, `padaliniokodas`, `iskodas`) VALUES (NULL, 'PA10', 'IS7');
INSERT INTO `nocode`.`app_ispadaliniai` (`id`, `padaliniokodas`, `iskodas`) VALUES (NULL, 'PA10', 'IS10');
INSERT INTO `nocode`.`app_ispadaliniai` (`id`, `padaliniokodas`, `iskodas`) VALUES (NULL, 'PA11', 'IS1');
INSERT INTO `nocode`.`app_ispadaliniai` (`id`, `padaliniokodas`, `iskodas`) VALUES (NULL, 'PA11', 'IS2');
INSERT INTO `nocode`.`app_ispadaliniai` (`id`, `padaliniokodas`, `iskodas`) VALUES (NULL, 'PA12', 'IS1');
INSERT INTO `nocode`.`app_ispadaliniai` (`id`, `padaliniokodas`, `iskodas`) VALUES (NULL, 'PA12', 'IS2');
INSERT INTO `nocode`.`app_ispadaliniai` (`id`, `padaliniokodas`, `iskodas`) VALUES (NULL, 'PA12', 'IS4');
INSERT INTO `nocode`.`app_ispadaliniai` (`id`, `padaliniokodas`, `iskodas`) VALUES (NULL, 'PA12', 'IS7');
INSERT INTO `nocode`.`app_ispadaliniai` (`id`, `padaliniokodas`, `iskodas`) VALUES (NULL, 'PA12', 'IS10');

INSERT INTO `nocode`.`app_priemonepadaliniai` (`id`, `padaliniokodas`, `priemoneskodas`, `valandos`) VALUES (NULL, 'PA1', 'p1-1', 1);
INSERT INTO `nocode`.`app_priemonepadaliniai` (`id`, `padaliniokodas`, `priemoneskodas`, `valandos`) VALUES (NULL, 'PA1', 'p1-3', 1);
INSERT INTO `nocode`.`app_priemonepadaliniai` (`id`, `padaliniokodas`, `priemoneskodas`, `valandos`) VALUES (NULL, 'PA1', 'p1-5', 1);
INSERT INTO `nocode`.`app_priemonepadaliniai` (`id`, `padaliniokodas`, `priemoneskodas`, `valandos`) VALUES (NULL, 'PA1', 'p1-9', 1);
INSERT INTO `nocode`.`app_priemonepadaliniai` (`id`, `padaliniokodas`, `priemoneskodas`, `valandos`) VALUES (NULL, 'PA1', 'P2-1', 1);
INSERT INTO `nocode`.`app_priemonepadaliniai` (`id`, `padaliniokodas`, `priemoneskodas`, `valandos`) VALUES (NULL, 'PA1', 'P2-7', 1);
INSERT INTO `nocode`.`app_priemonepadaliniai` (`id`, `padaliniokodas`, `priemoneskodas`, `valandos`) VALUES (NULL, 'PA1', 'P3-2', 1);
INSERT INTO `nocode`.`app_priemonepadaliniai` (`id`, `padaliniokodas`, `priemoneskodas`, `valandos`) VALUES (NULL, 'PA1', 'P4-1', 1);
INSERT INTO `nocode`.`app_priemonepadaliniai` (`id`, `padaliniokodas`, `priemoneskodas`, `valandos`) VALUES (NULL, 'PA2', 'p1-1', 1);
INSERT INTO `nocode`.`app_priemonepadaliniai` (`id`, `padaliniokodas`, `priemoneskodas`, `valandos`) VALUES (NULL, 'PA2', 'p1-2', 0.5);
INSERT INTO `nocode`.`app_priemonepadaliniai` (`id`, `padaliniokodas`, `priemoneskodas`, `valandos`) VALUES (NULL, 'PA2', 'p1-3', 0.5);
INSERT INTO `nocode`.`app_priemonepadaliniai` (`id`, `padaliniokodas`, `priemoneskodas`, `valandos`) VALUES (NULL, 'PA2', 'p1-7', 1);
INSERT INTO `nocode`.`app_priemonepadaliniai` (`id`, `padaliniokodas`, `priemoneskodas`, `valandos`) VALUES (NULL, 'PA2', 'P2-3', 1);
INSERT INTO `nocode`.`app_priemonepadaliniai` (`id`, `padaliniokodas`, `priemoneskodas`, `valandos`) VALUES (NULL, 'PA2', 'P2-9', 1);
INSERT INTO `nocode`.`app_priemonepadaliniai` (`id`, `padaliniokodas`, `priemoneskodas`, `valandos`) VALUES (NULL, 'PA2', 'P3-5', 1);
INSERT INTO `nocode`.`app_priemonepadaliniai` (`id`, `padaliniokodas`, `priemoneskodas`, `valandos`) VALUES (NULL, 'PA2', 'P4-3', 1);
INSERT INTO `nocode`.`app_priemonepadaliniai` (`id`, `padaliniokodas`, `priemoneskodas`, `valandos`) VALUES (NULL, 'PA3', 'p1-4', 0.5);
INSERT INTO `nocode`.`app_priemonepadaliniai` (`id`, `padaliniokodas`, `priemoneskodas`, `valandos`) VALUES (NULL, 'PA3', 'p1-6', 1);
INSERT INTO `nocode`.`app_priemonepadaliniai` (`id`, `padaliniokodas`, `priemoneskodas`, `valandos`) VALUES (NULL, 'PA3', 'p1-10', 1);
INSERT INTO `nocode`.`app_priemonepadaliniai` (`id`, `padaliniokodas`, `priemoneskodas`, `valandos`) VALUES (NULL, 'PA3', 'P2-5', 1);
INSERT INTO `nocode`.`app_priemonepadaliniai` (`id`, `padaliniokodas`, `priemoneskodas`, `valandos`) VALUES (NULL, 'PA3', 'P2-6', 0.5);
INSERT INTO `nocode`.`app_priemonepadaliniai` (`id`, `padaliniokodas`, `priemoneskodas`, `valandos`) VALUES (NULL, 'PA3', 'P3-3', 0.5);
INSERT INTO `nocode`.`app_priemonepadaliniai` (`id`, `padaliniokodas`, `priemoneskodas`, `valandos`) VALUES (NULL, 'PA3', 'P4-2', 0.5);
INSERT INTO `nocode`.`app_priemonepadaliniai` (`id`, `padaliniokodas`, `priemoneskodas`, `valandos`) VALUES (NULL, 'PA4', 'p1-1', 0.5);
INSERT INTO `nocode`.`app_priemonepadaliniai` (`id`, `padaliniokodas`, `priemoneskodas`, `valandos`) VALUES (NULL, 'PA4', 'p1-2', 1);
INSERT INTO `nocode`.`app_priemonepadaliniai` (`id`, `padaliniokodas`, `priemoneskodas`, `valandos`) VALUES (NULL, 'PA4', 'p1-5', 0.5);
INSERT INTO `nocode`.`app_priemonepadaliniai` (`id`, `padaliniokodas`, `priemoneskodas`, `valandos`) VALUES (NULL, 'PA4', 'p1-8', 0.5);
INSERT INTO `nocode`.`app_priemonepadaliniai` (`id`, `padaliniokodas`, `priemoneskodas`, `valandos`) VALUES (NULL, 'PA4', 'P2-3', 1);
INSERT INTO `nocode`.`app_priemonepadaliniai` (`id`, `padaliniokodas`, `priemoneskodas`, `valandos`) VALUES (NULL, 'PA4', 'P2-7', 1);
INSERT INTO `nocode`.`app_priemonepadaliniai` (`id`, `padaliniokodas`, `priemoneskodas`, `valandos`) VALUES (NULL, 'PA4', 'P3-4', 0.5);
INSERT INTO `nocode`.`app_priemonepadaliniai` (`id`, `padaliniokodas`, `priemoneskodas`, `valandos`) VALUES (NULL, 'PA4', 'P4-1', 1);
INSERT INTO `nocode`.`app_priemonepadaliniai` (`id`, `padaliniokodas`, `priemoneskodas`, `valandos`) VALUES (NULL, 'PA12', 'p1-2', 0.5);
INSERT INTO `nocode`.`app_priemonepadaliniai` (`id`, `padaliniokodas`, `priemoneskodas`, `valandos`) VALUES (NULL, 'PA12', 'p1-5', 1);
INSERT INTO `nocode`.`app_priemonepadaliniai` (`id`, `padaliniokodas`, `priemoneskodas`, `valandos`) VALUES (NULL, 'PA12', 'p1-6', 1);
INSERT INTO `nocode`.`app_priemonepadaliniai` (`id`, `padaliniokodas`, `priemoneskodas`, `valandos`) VALUES (NULL, 'PA12', 'P2-3', 0.5);
INSERT INTO `nocode`.`app_priemonepadaliniai` (`id`, `padaliniokodas`, `priemoneskodas`, `valandos`) VALUES (NULL, 'PA12', 'P2-4', 1);
INSERT INTO `nocode`.`app_priemonepadaliniai` (`id`, `padaliniokodas`, `priemoneskodas`, `valandos`) VALUES (NULL, 'PA12', 'P3-3', 0.5);
INSERT INTO `nocode`.`app_priemonepadaliniai` (`id`, `padaliniokodas`, `priemoneskodas`, `valandos`) VALUES (NULL, 'PA5', 'p1-2', 0.5);
INSERT INTO `nocode`.`app_priemonepadaliniai` (`id`, `padaliniokodas`, `priemoneskodas`, `valandos`) VALUES (NULL, 'PA5', 'p1-4', 1);
INSERT INTO `nocode`.`app_priemonepadaliniai` (`id`, `padaliniokodas`, `priemoneskodas`, `valandos`) VALUES (NULL, 'PA5', 'p1-10', 0.5);
INSERT INTO `nocode`.`app_priemonepadaliniai` (`id`, `padaliniokodas`, `priemoneskodas`, `valandos`) VALUES (NULL, 'PA5', 'P2-5', 1);
INSERT INTO `nocode`.`app_priemonepadaliniai` (`id`, `padaliniokodas`, `priemoneskodas`, `valandos`) VALUES (NULL, 'PA5', 'P3-1', 0.5);
INSERT INTO `nocode`.`app_priemonepadaliniai` (`id`, `padaliniokodas`, `priemoneskodas`, `valandos`) VALUES (NULL, 'PA5', 'P4-2', 1);
INSERT INTO `nocode`.`app_priemonepadaliniai` (`id`, `padaliniokodas`, `priemoneskodas`, `valandos`) VALUES (NULL, 'PA5', 'P4-3', 1);
INSERT INTO `nocode`.`app_priemonepadaliniai` (`id`, `padaliniokodas`, `priemoneskodas`, `valandos`) VALUES (NULL, 'PA6', 'p1-8', 1);
INSERT INTO `nocode`.`app_priemonepadaliniai` (`id`, `padaliniokodas`, `priemoneskodas`, `valandos`) VALUES (NULL, 'PA6', 'P2-2', 1);
INSERT INTO `nocode`.`app_priemonepadaliniai` (`id`, `padaliniokodas`, `priemoneskodas`, `valandos`) VALUES (NULL, 'PA6', 'P2-4', 0.5);
INSERT INTO `nocode`.`app_priemonepadaliniai` (`id`, `padaliniokodas`, `priemoneskodas`, `valandos`) VALUES (NULL, 'PA6', 'P2-9', 2);
INSERT INTO `nocode`.`app_priemonepadaliniai` (`id`, `padaliniokodas`, `priemoneskodas`, `valandos`) VALUES (NULL, 'PA6', 'P3-4', 2);
INSERT INTO `nocode`.`app_priemonepadaliniai` (`id`, `padaliniokodas`, `priemoneskodas`, `valandos`) VALUES (NULL, 'PA6', 'P4-2', 1);
INSERT INTO `nocode`.`app_priemonepadaliniai` (`id`, `padaliniokodas`, `priemoneskodas`, `valandos`) VALUES (NULL, 'PA7', 'p1-1', 1);
INSERT INTO `nocode`.`app_priemonepadaliniai` (`id`, `padaliniokodas`, `priemoneskodas`, `valandos`) VALUES (NULL, 'PA7', 'p1-2', 0.5);
INSERT INTO `nocode`.`app_priemonepadaliniai` (`id`, `padaliniokodas`, `priemoneskodas`, `valandos`) VALUES (NULL, 'PA7', 'p1-3', 1);
INSERT INTO `nocode`.`app_priemonepadaliniai` (`id`, `padaliniokodas`, `priemoneskodas`, `valandos`) VALUES (NULL, 'PA7', 'p1-5', 0.5);
INSERT INTO `nocode`.`app_priemonepadaliniai` (`id`, `padaliniokodas`, `priemoneskodas`, `valandos`) VALUES (NULL, 'PA7', 'P2-8', 2);
INSERT INTO `nocode`.`app_priemonepadaliniai` (`id`, `padaliniokodas`, `priemoneskodas`, `valandos`) VALUES (NULL, 'PA7', 'P3-5', 0.5);
INSERT INTO `nocode`.`app_priemonepadaliniai` (`id`, `padaliniokodas`, `priemoneskodas`, `valandos`) VALUES (NULL, 'PA8', 'p1-4', 1);
INSERT INTO `nocode`.`app_priemonepadaliniai` (`id`, `padaliniokodas`, `priemoneskodas`, `valandos`) VALUES (NULL, 'PA8', 'p1-6', 0.5);
INSERT INTO `nocode`.`app_priemonepadaliniai` (`id`, `padaliniokodas`, `priemoneskodas`, `valandos`) VALUES (NULL, 'PA8', 'p1-7', 0.5);
INSERT INTO `nocode`.`app_priemonepadaliniai` (`id`, `padaliniokodas`, `priemoneskodas`, `valandos`) VALUES (NULL, 'PA8', 'p1-8', 0.5);
INSERT INTO `nocode`.`app_priemonepadaliniai` (`id`, `padaliniokodas`, `priemoneskodas`, `valandos`) VALUES (NULL, 'PA8', 'p1-9', 0.5);
INSERT INTO `nocode`.`app_priemonepadaliniai` (`id`, `padaliniokodas`, `priemoneskodas`, `valandos`) VALUES (NULL, 'PA8', 'P2-3', 0.5);
INSERT INTO `nocode`.`app_priemonepadaliniai` (`id`, `padaliniokodas`, `priemoneskodas`, `valandos`) VALUES (NULL, 'PA8', 'P2-6', 0.5);
INSERT INTO `nocode`.`app_priemonepadaliniai` (`id`, `padaliniokodas`, `priemoneskodas`, `valandos`) VALUES (NULL, 'PA8', 'P3-1', 0.5);
INSERT INTO `nocode`.`app_priemonepadaliniai` (`id`, `padaliniokodas`, `priemoneskodas`, `valandos`) VALUES (NULL, 'PA8', 'P4-3', 1);
INSERT INTO `nocode`.`app_priemonepadaliniai` (`id`, `padaliniokodas`, `priemoneskodas`, `valandos`) VALUES (NULL, 'PA9', 'P2-1', 0.5);
INSERT INTO `nocode`.`app_priemonepadaliniai` (`id`, `padaliniokodas`, `priemoneskodas`, `valandos`) VALUES (NULL, 'PA9', 'P2-6', 1);
INSERT INTO `nocode`.`app_priemonepadaliniai` (`id`, `padaliniokodas`, `priemoneskodas`, `valandos`) VALUES (NULL, 'PA9', 'P2-8', 0.5);
INSERT INTO `nocode`.`app_priemonepadaliniai` (`id`, `padaliniokodas`, `priemoneskodas`, `valandos`) VALUES (NULL, 'PA9', 'P3-3', 0.5);
INSERT INTO `nocode`.`app_priemonepadaliniai` (`id`, `padaliniokodas`, `priemoneskodas`, `valandos`) VALUES (NULL, 'PA9', 'P4-2', 1);
INSERT INTO `nocode`.`app_priemonepadaliniai` (`id`, `padaliniokodas`, `priemoneskodas`, `valandos`) VALUES (NULL, 'PA10', 'p1-1', 0.5);
INSERT INTO `nocode`.`app_priemonepadaliniai` (`id`, `padaliniokodas`, `priemoneskodas`, `valandos`) VALUES (NULL, 'PA10', 'p1-2', 1);
INSERT INTO `nocode`.`app_priemonepadaliniai` (`id`, `padaliniokodas`, `priemoneskodas`, `valandos`) VALUES (NULL, 'PA10', 'p1-3', 0.5);
INSERT INTO `nocode`.`app_priemonepadaliniai` (`id`, `padaliniokodas`, `priemoneskodas`, `valandos`) VALUES (NULL, 'PA10', 'P2-1', 0.5);
INSERT INTO `nocode`.`app_priemonepadaliniai` (`id`, `padaliniokodas`, `priemoneskodas`, `valandos`) VALUES (NULL, 'PA10', 'P3-1', 0.5);
INSERT INTO `nocode`.`app_priemonepadaliniai` (`id`, `padaliniokodas`, `priemoneskodas`, `valandos`) VALUES (NULL, 'PA10', 'P3-2', 2);
INSERT INTO `nocode`.`app_priemonepadaliniai` (`id`, `padaliniokodas`, `priemoneskodas`, `valandos`) VALUES (NULL, 'PA10', 'P3-5', 1);
INSERT INTO `nocode`.`app_priemonepadaliniai` (`id`, `padaliniokodas`, `priemoneskodas`, `valandos`) VALUES (NULL, 'PA10', 'P4-1', 1);
INSERT INTO `nocode`.`app_priemonepadaliniai` (`id`, `padaliniokodas`, `priemoneskodas`, `valandos`) VALUES (NULL, 'PA10', 'P4-3', 1);
INSERT INTO `nocode`.`app_priemonepadaliniai` (`id`, `padaliniokodas`, `priemoneskodas`, `valandos`) VALUES (NULL, 'PA11', 'p1-5', 1);
INSERT INTO `nocode`.`app_priemonepadaliniai` (`id`, `padaliniokodas`, `priemoneskodas`, `valandos`) VALUES (NULL, 'PA11', 'p1-7', 0.5);
INSERT INTO `nocode`.`app_priemonepadaliniai` (`id`, `padaliniokodas`, `priemoneskodas`, `valandos`) VALUES (NULL, 'PA11', 'p1-9', 0.5);
INSERT INTO `nocode`.`app_priemonepadaliniai` (`id`, `padaliniokodas`, `priemoneskodas`, `valandos`) VALUES (NULL, 'PA11', 'p1-10', 1);
INSERT INTO `nocode`.`app_priemonepadaliniai` (`id`, `padaliniokodas`, `priemoneskodas`, `valandos`) VALUES (NULL, 'PA11', 'P2-2', 0.5);
INSERT INTO `nocode`.`app_priemonepadaliniai` (`id`, `padaliniokodas`, `priemoneskodas`, `valandos`) VALUES (NULL, 'PA11', 'P2-4', 0.5);
INSERT INTO `nocode`.`app_priemonepadaliniai` (`id`, `padaliniokodas`, `priemoneskodas`, `valandos`) VALUES (NULL, 'PA11', 'P3-1', 0.5);
INSERT INTO `nocode`.`app_priemonepadaliniai` (`id`, `padaliniokodas`, `priemoneskodas`, `valandos`) VALUES (NULL, 'PA11', 'P3-5', 0.5);